# Probability I

## Concepts

### Frequentist Vs. Bayesian {.unnumbered}

The **frequentist** interpretation assumes that probabilities represent proportions of specific events occurring over infinitely identical trials.

The **Bayesian** interpretation assumes that probabilities are subjective beliefs about the relative likelihood of events.

### Experiments and Sets {.unnumbered}

An **experiment** is a process that leads to one of several outcomes. Ex: Tossing a Die, Tossing a Coin, Drawing a Card, etc.

An **outcome** is the result of an experiment. Ex: A coin landing on heads, drawing the ace of spades.

The **sample space** $(S)$ of an experiment contains all possible outcomes of the experiment. Ex: $S$={$1$,$2$,$3$,$4$,$5$,$6$} is the sample space for tossing a die.

An **event** is a subset of the sample space. $A$={$2$,$4$,$6$} is the event of tossing an even number when rolling a die.

### Basic Probability Concepts {.unnumbered}

A **probability** is a numerical value that measures the likelihood that an event occurs.

To calculate **probabilities**, find the ratio between favorable outcomes and total outcomes. $p=favorable/total$.

-   The probability of any event $A$ is a value between $0$ and $1$ inclusive. Formally, $0\leq P(A) \leq1$.

-   When the probability of the event is $0$ then the event is impossible. When the probability is $1$ then the event is certain.

-   The sum of the probabilities of a list of **mutually exclusive** and **exhaustive** events equals $1$. Formally, $\sum P(x_i)=1$.

    -   **Mutually exclusive** events do not share any common outcomes. The occurrence of one event precludes the occurrence of others.

    -   **Exhaustive** events include all outcomes in the sample space.

To assign probabilities you can use the Empirical, Classical, or Subjective Methods.

-   **Empirical**: calculated as a relative frequency of occurrence.

-   **Classical**: based on logical analysis.

-   **Subjective**: calculated by drawing on personal and subjective judgement.

### Probability Rules {.unnumbered}

The **Complement Rule**: $P(A^c)=1-P(A)$, where $A^c$ is the complement of $A$.

The **Addition Rule**: $P(A \cup B)=P(A)+P(B)-P(A \cap B)$, where $\cap$ is intersection and $\cup$ is union.

The **Multiplication Rule**:

-   if events are dependent $P(A \cap B)= P(A|B)P(B)$, where $P(A|B)$ is the conditional probability.

-   if events are independent $P(A \cap B)= P(A)P(B)$.

The **Law of Total Probability**: $P(A)=P(A|B)P(B)+P(A|B^c)P(B^c)$.

**Bayes' Theorem**: $P(A|B)=P(B|A)P(A)/P(B)$.

### Counting Rules {.unnumbered}

The **Combination** function counts the number of ways to choose $x$ objects from a total of $n$ objects. The order in which the $x$ objects are listed does not matter.

-   If repetition is not allowed use $C_n^x= \frac{n!}{(n-x)!x!}$.

-   If repetition is allowed use $\frac{(x+n-1)!}{(n-1)!x!}$.

The **Permutation** function also counts the number of ways to choose $x$ objects from a total of $n$ objects. However, the order in which the $x$ objects are listed does matter.

-   If repetition is not allowed use $P_n^x= \frac{n!}{(n-x)!}$.

-   If repetition is allowed use $n^x$.

### Useful R Functions {.unnumbered}

The `table()` function can be used to construct frequency distributions.

The `factorial()` function returns the factorial of a number.

The `gtools` package contains the `combinations()` and `permutations()` functions used to calculate combinations and permutations. Use the *repeats.allowed* argument to specify counting with repetition or no repetition. The *v* argument allows you to specify a vector of elements.

## Exercises

The following exercises will help you practice some probability concepts and formulas. In particular, the exercises work on:

-   Calculating simple probabilities.

-   Applying probability rules.

-   Using counting rules.

Answers are provided below. Try not to peak until you have a formulated your own answer and double checked your work for any mistakes.

### Exercise 1 {.unnumbered}

For the following exercises, make your calculations by hand and verify results with a calculator or R.

1.  A sample space $S$ yields five equally likely events, $A$, $B$, $C$, $D$, and $E$. Find $P(D)$, $P(B^c)$, and $P(A \cup C \cup E)$.

2.  Consider the roll of a die. Define $A$ as {1,2,3}, $B$ as {1,2,3,5,6}, $C$ as {4,6}, and $D$ as {4,5,6}. Are the events $A$ and $B$ mutually exclusive, exhaustive, both or none? What about events $A$ and $D$?

3.  A recent study suggests that $33.1$% of the adult U.S. population is overweight and $35.7$% obese. What is the probability that a randomly selected adult in the U.S. is either obese or overweight? What is the probability that their weight is normal? Are the events mutually exclusive and exhaustive?

### Exercise 2 {.unnumbered}

For the following exercises, make your calculations by hand and verify results with a calculator or R.

1.  Let $P(A)=0.65$, $P(B)=0.3$, and $P(A|B)=0.45$. Calculate $P(A \cap B)$, $P(A \cup B)$, and $P(B|A)$.

2.  Let $P(A)=0.4$, $P(B)=0.5$, and $P(A^c \cap B^c)=0.24$. Calculate $P(A^c|B^c)$, $P(A^c \cup B^c)$, and $P(A \cup B)$.

3.  Stock $A$ will rise in price with a probability of $0.4$, stock $B$ will rise with a probability of $0.6$. If stock $B$ rises in price, then $A$ will also rise with a probability of $0.5$. What is the probability that at least one of the stocks will rise in price? Prove that events $A$ and $B$ are (are not) mutually exclusive (independent).

### Exercise 3 {.unnumbered}

1.  Create a joint probability table from the contingency table below. Find $P(A)$, $P(A \cap B)$, $P(A|B)$, and $P(B|A^c)$. Determine whether the events are independent or mutually exclusive.

|     |       |       |
|-----|-------|-------|
|     | $A^c$ | $B^c$ |
| $A$ | 26    | 34    |
| $B$ | 14    | 26    |

### Exercise 4 {.unnumbered}

You will need the **Crash** data set and R to answer this question. The data shows information on several car crashes. Specifically, if the crash was Head-On or Not Head-On and whether there was Daylight or No Daylight.

1.  Create a contingency table.

2.  Find the probability that a) a car crash is Head-On, b) a car crash is in daylight c) a car crash is Head-On given that there is daylight.

3.  Show that Crashes and Light are dependent.

### Exercise 5 {.unnumbered}

1.  Use Bayes' Theorem in the following question. Let $P(A)=0.7$, $P(B|A)=0.55$, and $P(B|A^c)=0.10$. Find $P(A^c)$, $P(A \cap B)$, $P(A^c \cap B)$, $P(B)$, and $P(A|B)$.

2.  Some find tutors helpful when taking a course. Julia has a 40% chance to fail a course if she does not have a tutor. With a tutor, the probability of failing is only 10%. There is a 50% chance that Julia finds an available tutor. What is the probability that Julia will fail the course? If she ends up failing the course, what is the probability that she had a tutor?

### Exercise 6 {.unnumbered}

1.  Calculate the following values and verify your results using R. a) 3!, b) 4!, c) $C_6^8$, d) $P_6^8$.

2.  There are 10 players in a local basketball team. If we chose 5 players to randomly start a game, in how many ways can we select the five players if order doesn't matter? What if order matters?

## Answers
