<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.6.32">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>8&nbsp; Probability I – Business Statistics</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./ProbabilityII.html" rel="next">
<link href="./RegressionII.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-2486e1f0a3ee9ee1fc393803a1361cdb.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-9904b5196d746cb5bc47063911474b57.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<link href="site_libs/quarto-contrib/fontawesome6-6.7.2/all.min.css" rel="stylesheet">
<link href="site_libs/quarto-contrib/fontawesome6-6.7.2/latex-fontsize.css" rel="stylesheet">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<script async="" src="https://www.googletagmanager.com/gtag/js?id=G-PLNY5BZ16X"></script>

<script type="text/javascript">

window.dataLayer = window.dataLayer || [];
function gtag(){dataLayer.push(arguments);}
gtag('js', new Date());
gtag('config', 'G-PLNY5BZ16X', { 'anonymize_ip': true});
</script>
<!-- Google tag (gtag.js) -->
<script async="" src="https://www.googletagmanager.com/gtag/js?id=G-FWC3RCL4BF"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'G-FWC3RCL4BF');
</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="nav-sidebar floating">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./ProbabilityI.html"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Probability I</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">Business Statistics</a> 
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Introduction</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./DescriptiveI.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Descriptive Stats I</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./DescriptiveII.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Descriptive Stats II</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./DescriptiveIII.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Descriptive Statistics III</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./DescriptiveIV.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Descriptive Stats IV</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./DescriptiveV.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Descriptive Stats V</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./RegressionI.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Regression I</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./RegressionII.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Regression II</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./ProbabilityI.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Probability I</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./ProbabilityII.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Probability II</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./ProbabilityIII.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Probability III</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./InferenceI.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Inference I</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./InferenceII.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Inference II</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./InferenceIII.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">Inference III</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./InfReg.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">14</span>&nbsp; <span class="chapter-title">Regression and Inference</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Excel Basics.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">15</span>&nbsp; <span class="chapter-title">Excel Basics</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./references.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">References</span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#frequentist-vs.-bayesian-statistics" id="toc-frequentist-vs.-bayesian-statistics" class="nav-link active" data-scroll-target="#frequentist-vs.-bayesian-statistics"><span class="header-section-number">8.1</span> Frequentist Vs. Bayesian Statistics</a></li>
  <li><a href="#experiments-and-sets" id="toc-experiments-and-sets" class="nav-link" data-scroll-target="#experiments-and-sets"><span class="header-section-number">8.2</span> Experiments and Sets</a></li>
  <li><a href="#basic-probability-concepts" id="toc-basic-probability-concepts" class="nav-link" data-scroll-target="#basic-probability-concepts"><span class="header-section-number">8.3</span> Basic Probability Concepts</a></li>
  <li><a href="#venn-diagram" id="toc-venn-diagram" class="nav-link" data-scroll-target="#venn-diagram"><span class="header-section-number">8.4</span> Venn Diagram</a></li>
  <li><a href="#probability-rules" id="toc-probability-rules" class="nav-link" data-scroll-target="#probability-rules"><span class="header-section-number">8.5</span> Probability Rules</a>
  <ul class="collapse">
  <li><a href="#complement-rule" id="toc-complement-rule" class="nav-link" data-scroll-target="#complement-rule">Complement Rule</a></li>
  <li><a href="#de-morgans-laws" id="toc-de-morgans-laws" class="nav-link" data-scroll-target="#de-morgans-laws">De Morgan’s Laws</a></li>
  <li><a href="#addition-rule" id="toc-addition-rule" class="nav-link" data-scroll-target="#addition-rule">Addition Rule</a></li>
  <li><a href="#multiplication-rule" id="toc-multiplication-rule" class="nav-link" data-scroll-target="#multiplication-rule">Multiplication Rule</a></li>
  <li><a href="#law-of-total-probability" id="toc-law-of-total-probability" class="nav-link" data-scroll-target="#law-of-total-probability">Law of Total Probability</a></li>
  <li><a href="#bayes-theorem" id="toc-bayes-theorem" class="nav-link" data-scroll-target="#bayes-theorem">Bayes’ Theorem</a></li>
  </ul></li>
  <li><a href="#contingency-tables" id="toc-contingency-tables" class="nav-link" data-scroll-target="#contingency-tables"><span class="header-section-number">8.6</span> Contingency Tables</a></li>
  <li><a href="#counting-rules" id="toc-counting-rules" class="nav-link" data-scroll-target="#counting-rules"><span class="header-section-number">8.7</span> Counting Rules</a>
  <ul class="collapse">
  <li><a href="#the-fundamental-counting-principle" id="toc-the-fundamental-counting-principle" class="nav-link" data-scroll-target="#the-fundamental-counting-principle">The Fundamental Counting Principle</a></li>
  <li><a href="#factorial" id="toc-factorial" class="nav-link" data-scroll-target="#factorial">Factorial</a></li>
  <li><a href="#combinations" id="toc-combinations" class="nav-link" data-scroll-target="#combinations">Combinations</a></li>
  <li><a href="#permutations" id="toc-permutations" class="nav-link" data-scroll-target="#permutations">Permutations</a></li>
  </ul></li>
  <li><a href="#probability-in-excel" id="toc-probability-in-excel" class="nav-link" data-scroll-target="#probability-in-excel"><span class="header-section-number">8.8</span> Probability in Excel</a></li>
  <li><a href="#excel-function-summary" id="toc-excel-function-summary" class="nav-link" data-scroll-target="#excel-function-summary"><span class="header-section-number">8.9</span> Excel Function Summary</a></li>
  <li><a href="#chapter-summary-cheat-sheet" id="toc-chapter-summary-cheat-sheet" class="nav-link" data-scroll-target="#chapter-summary-cheat-sheet"><span class="header-section-number">8.10</span> Chapter Summary Cheat Sheet</a></li>
  <li><a href="#exercises" id="toc-exercises" class="nav-link" data-scroll-target="#exercises"><span class="header-section-number">8.11</span> Exercises</a>
  <ul class="collapse">
  <li><a href="#exercise-1" id="toc-exercise-1" class="nav-link" data-scroll-target="#exercise-1">Exercise 1</a></li>
  <li><a href="#exercise-2" id="toc-exercise-2" class="nav-link" data-scroll-target="#exercise-2">Exercise 2</a></li>
  <li><a href="#exercise-3" id="toc-exercise-3" class="nav-link" data-scroll-target="#exercise-3">Exercise 3</a></li>
  <li><a href="#exercise-4" id="toc-exercise-4" class="nav-link" data-scroll-target="#exercise-4">Exercise 4</a></li>
  <li><a href="#exercise-5" id="toc-exercise-5" class="nav-link" data-scroll-target="#exercise-5">Exercise 5</a></li>
  <li><a href="#exercise-6" id="toc-exercise-6" class="nav-link" data-scroll-target="#exercise-6">Exercise 6</a></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Probability I</span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<style>
details {
  background-color: #F8F9FA;
  padding: 5px;
  border: 1px solid #ddd; /* Light border */
  border-radius: 5px; /* Rounded corners */
  margin: 10px 0; /* Spacing */
}

details summary {
  cursor: pointer; /* Pointer cursor for interactivity */
}
</style>
<p>Decision-making under uncertainty is at the core of business strategy, risk management, and forecasting. This section will study tools and concepts that will make us smarter when making data-driven decisions. Mastering probability in finance, marketing, supply chain, or operations helps professionals analyze risks, optimize strategies, and stay competitive in uncertain environments. We start with the basic concepts and ideas of probability below. Probability marks a turning point in the book. Until now we have described data we already collected; from here we build the mathematics of uncertainty — the bridge that will later let us reason from an imperfect sample back to the world that produced it.</p>
<section id="frequentist-vs.-bayesian-statistics" class="level2" data-number="8.1">
<h2 data-number="8.1" class="anchored" data-anchor-id="frequentist-vs.-bayesian-statistics"><span class="header-section-number">8.1</span> Frequentist Vs. Bayesian Statistics</h2>
<p>There are two interpretations of probability. The <strong>frequentist</strong> interpretation assumes that probabilities represent proportions of specific events occurring over infinitely identical trials. In contrast, the <strong>Bayesian</strong> interpretation assumes that probabilities are subjective beliefs about the relative likelihood of events. Despite their philosophical differences, both approaches adhere to the core rules of probability —including the Addition Rule, Multiplication Rule, and Bayes’ Theorem— which provide a consistent mathematical foundation for making probabilistic inferences.</p>
<div class="callout-example">
<p><strong>Example:</strong> A company might use frequentist statistics to determine the average return rate of a product, but apply Bayesian methods to adjust sales forecasts based on changing consumer behavior.</p>
</div>
</section>
<section id="experiments-and-sets" class="level2" data-number="8.2">
<h2 data-number="8.2" class="anchored" data-anchor-id="experiments-and-sets"><span class="header-section-number">8.2</span> Experiments and Sets</h2>
<p>The following concepts form the foundation of probability theory. They provide a structure that is useful when analyzing uncertainty and randomness.</p>
<ul>
<li><p>An <strong>experiment</strong> is a process that leads to one of several outcomes. <em>Ex: Tossing a Die, Tossing a Coin, Drawing a Card, etc.</em></p></li>
<li><p>An <strong>outcome</strong> is the result of an experiment. <em>Ex: A coin landing on heads, drawing the ace of spades.</em></p></li>
<li><p>The <strong>sample space</strong> <span class="math inline">\((S)\)</span> of an experiment contains all possible outcomes of the experiment. <em>Ex:</em> <span class="math inline">\(S=\{1,2,3,4,5,6\}\)</span> is the sample space for tossing a die.</p></li>
<li><p>An <strong>event</strong> is a subset of the sample space. <em>Ex:</em> <span class="math inline">\(A=\{2,4,6\}\)</span> is the event of tossing an even number when rolling a die. <span class="math inline">\(B=\{1A,1D,1S,1H\}\)</span> is the event of drawing an ace from a deck of cards.</p></li>
</ul>
</section>
<section id="basic-probability-concepts" class="level2" data-number="8.3">
<h2 data-number="8.3" class="anchored" data-anchor-id="basic-probability-concepts"><span class="header-section-number">8.3</span> Basic Probability Concepts</h2>
<p>A <strong>probability</strong> is a numerical value that measures the likelihood that an event occurs. To calculate <strong>probabilities</strong>, we find the ratio between favorable outcomes and total outcomes. Hence, the probability of an event is given by:</p>
<div class="callout-formula">
<p><strong>PROBABILITY OF AN EVENT</strong> <span class="math display">\[P(A)=\frac{Number\ of\ outcomes\ in\ A}{Number\ of\ outcomes\ in\ Sample \ Space}\]</span></p>
</div>
<p>The probability of A satisfies <span class="math inline">\(0\leq P(A) \leq1\)</span>. Since A is a subset of S, the number of elements in A is at most that of the sample space S. Hence, if A=S, then P(A)=1. If A is a null event (i.e., has no elements) P(A)=0 and is impossible. We can conclude that P(A) ranges from 0 to 1, inclusive.</p>
<p>In many cases, we analyze how multiple events interact within the sample space, particularly when they either exclude each other or collectively cover all possible outcomes.<strong>Mutually exclusive</strong> events do not share any common outcomes. The occurrence of one event precludes the occurrence of others. <strong>Exhaustive</strong> events include all outcomes in the sample space.</p>
<p>Given these concepts if follows that the sum of the probabilities of a list of <strong>mutually exclusive</strong> and <strong>exhaustive</strong> events equals <span class="math inline">\(1\)</span>. Formally, we state: <span class="math inline">\(\sum P(x_i)=1\)</span>, where <span class="math inline">\(x_i\)</span> is outcome <span class="math inline">\(i\)</span>.</p>
<div class="callout-example">
<p><strong>Example:</strong> Let’s consider a standard deck of 52 playing cards to illustrate the key probability concepts.</p>
<p>If we randomly draw one card from a standard deck, the sample space <span class="math inline">\(S\)</span> consists of all 52 cards. Suppose we define event <span class="math inline">\(A\)</span> as <em>drawing a red card</em>. Since there are 26 red cards, the probability is:</p>
<p><span class="math display">\[P(A) = \frac{\text{Number of red cards}}{\text{Total number of cards}} = \frac{26}{52} = 0.5\]</span></p>
<p>Since <span class="math inline">\(( 0 \leq P(A) \leq 1)\)</span>, this follows the basic probability rule. Next let’s consider mutually exclusive events. Let event <span class="math inline">\(B\)</span> be drawing a heart and event <span class="math inline">\(C\)</span> be drawing a spade. Since a single drawn card cannot be both a heart and a spade, these events are mutually exclusive.</p>
<p>The four suits (<em>hearts, diamonds, clubs, spades</em>) form an exhaustive set, because every card belongs to exactly one suit. The sum of their probabilities equals 1:</p>
<p><span class="math display">\[P(\text{hearts}) + P(\text{diamonds}) + P(\text{clubs}) + P(\text{spades}) = \frac{13}{52} + \frac{13}{52} + \frac{13}{52} + \frac{13}{52} = 1\]</span></p>
<p>Note that this also satisfies the rule <span class="math inline">\(\sum P(x_i) = 1\)</span>, where <span class="math inline">\(x_i\)</span> represents each possible outcome (suit).</p>
</div>
</section>
<section id="venn-diagram" class="level2" data-number="8.4">
<h2 data-number="8.4" class="anchored" data-anchor-id="venn-diagram"><span class="header-section-number">8.4</span> Venn Diagram</h2>
<p>A Venn diagram is a visual representation of sets and their relationships. It consists of overlapping circles, each representing a set. Below is an example:</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="images/venn.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:75.0%"></p>
</figure>
</div>
</div>
</div>
<p>The rectangle enclosing the circles represents the sample set (i.e., the 52 playing cards). Each circle represents a set or event The heart circle contains all 13 hearts; the same holds for the clubs circle. The area outside the circle that has hearts represents its complement, meaning elements that are clubs, spades, or diamonds. Since the two sets do not overlap, they are mutually exclusive (i.e., if a card is a heart, it can’t be a spade). The total area covered by both sets represents the <strong>union</strong> denoted by <span class="math inline">\(\cup\)</span>. This is the set that contains all elements that belong to at least one of the sets. Formally, we would represent this set as <span class="math inline">\((Hearts \cup Spades)\)</span>.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="images/venn2.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:75.0%"></p>
</figure>
</div>
</div>
</div>
<p>The overlapping region of two sets contains elements that belong to both sets. This region is called the <strong>intersection</strong>. The intersection contains elements that are Hearts and Jacks (i.e., the jack of hearts). Formally, we denote the intersection by <span class="math inline">\((Hearts \cap Jacks)\)</span>.</p>
</section>
<section id="probability-rules" class="level2" data-number="8.5">
<h2 data-number="8.5" class="anchored" data-anchor-id="probability-rules"><span class="header-section-number">8.5</span> Probability Rules</h2>
<p>Probability rules help us quantify uncertainty, avoid cognitive biases, and make rational predictions based on available data. These rules allow us to make reliable decisions. Below we introduce some useful rules.</p>
<section id="complement-rule" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="complement-rule">Complement Rule</h3>
<p>The <strong>Complement Rule</strong> states that:</p>
<div class="callout-formula">
<p><strong>THE COMPLEMENT RULE</strong> <span class="math display">\[P(A^c)=1-P(A)\]</span> where <span class="math inline">\(A^c\)</span> is the complement of <span class="math inline">\(A\)</span>.</p>
</div>
<p>This rule is useful when calculating probabilities for complex scenarios, where finding the probability of the complement is easier than computing the event itself.</p>
<div class="callout-example">
<p><strong>Example:</strong> The probability of drawing a spade, diamond or clubs can be estimated by just calculating the probability of drawing a heart. Since the probability of drawing a heart is <span class="math inline">\(P(Heart)=\frac{13}{52}\)</span>, then using the complement rule, <span class="math inline">\(P(Not \text{Heart})=1-\frac{13}{52}=\frac{39}{52}\)</span>.</p>
</div>
</section>
<section id="de-morgans-laws" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="de-morgans-laws">De Morgan’s Laws</h3>
<p><strong>De Morgan’s Laws</strong> relate the complement of a union to the complement of an intersection. They are handy for rewriting a complicated event as an easier-to-compute one.</p>
<div class="callout-formula">
<p><strong>DE MORGAN’S LAWS</strong> <span class="math display">\[(A \cup B)^c = A^c \cap B^c \qquad\qquad (A \cap B)^c = A^c \cup B^c\]</span> The complement of a union is the intersection of the complements, and the complement of an intersection is the union of the complements.</p>
</div>
<div class="callout-example">
<p><strong>Example:</strong> Roll a die with <span class="math inline">\(A=\{1,2,3\}\)</span> and <span class="math inline">\(B=\{2,4,6\}\)</span>. Their union is <span class="math inline">\(A \cup B=\{1,2,3,4,6\}\)</span>, so the complement is <span class="math inline">\((A \cup B)^c=\{5\}\)</span>. De Morgan’s Law gives the same answer from the complements: <span class="math inline">\(A^c \cap B^c=\{4,5,6\} \cap \{1,3,5\}=\{5\}\)</span>.</p>
</div>
</section>
<section id="addition-rule" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="addition-rule">Addition Rule</h3>
<p>The <strong>Addition Rule</strong> states:</p>
<div class="callout-formula">
<p><strong>THE ADDITION RULE</strong> <span class="math display">\[P(A \cup B)=P(A)+P(B)-P(A \cap B)\]</span> where <span class="math inline">\(\cap\)</span> is intersection and <span class="math inline">\(\cup\)</span> is union.</p>
</div>
<p>This formula prevents double-counting when events overlap by including the intersection of events.</p>
<div class="callout-example">
<p><strong>Example:</strong> Let’s calculate the probability of drawing either a heart or a face card. If we let event <span class="math inline">\(A\)</span> be drawing a heart, and event <span class="math inline">\(B\)</span> be drawing a face card, the probability is given by: <span class="math display">\[P(A \cup B)=\frac{13}{52}+\frac{12}{52}-\frac{3}{52}=\frac{22}{52}\]</span></p>
</div>
</section>
<section id="multiplication-rule" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="multiplication-rule">Multiplication Rule</h3>
<p>The <strong>Multiplication Rule</strong> states:</p>
<div class="callout-formula">
<p><strong>THE MULTIPLICATION RULE</strong> <span class="math display">\[P(A \cap B)= P(A|B)P(B)\]</span> where <span class="math inline">\(P(A|B)\)</span> is the conditional probability.</p>
</div>
<p><strong>Conditional probability</strong> measures the likelihood of an event occurring given that another event has already happened. If we reorganize the formula above we can get:</p>
<div class="callout-formula">
<p><strong>CONDITIONAL PROBABILITY</strong> <span class="math display">\[P(A|B)=\frac{P(A \cap B)}{P(B)}\]</span></p>
</div>
<p>Note that this formula focuses on cases where Event B has already occurred. We can then find the fraction of the cases where Event A also happens.</p>
<div class="callout-example">
<p><strong>Example:</strong> Suppose we randomly draw two cards from a standard deck of 52 cards, without replacement. The probability that both cards are aces is given by: <span class="math display">\[P(Ace \cap Ace)=P(Ace|Ace) \times P(Ace)= \frac {4}{52} \times \frac{3}{51}\]</span></p>
</div>
<p>Lastly, if events <span class="math inline">\(A\)</span> and <span class="math inline">\(B\)</span> are independent, we can simplify the multiplication rule to:</p>
<div class="callout-formula">
<p><strong>INDEPENDENCE</strong> <span class="math display">\[P(A \cap B)= P(A)P(B)\]</span></p>
</div>
<p>Hence, we can define independence as: events <span class="math inline">\(A\)</span> and <span class="math inline">\(B\)</span> are independent if the occurrence (or non occurrence) of one does not affect the probability of the other occurring.</p>
<div class="callout-example">
<p><strong>Example:</strong> Suppose we randomly draw a card from a standard deck, replace it, and then draw another card. The probability of drawing a heart in the first draw is <span class="math inline">\(13/52\)</span>, and the probability of drawing a spade in the second draw is also <span class="math inline">\(13/52\)</span>.</p>
</div>
<div class="callout-example">
<p><strong>Example:</strong> Suppose that the weather is sunny; this has no effect on the outcome of a lottery. Hence, the weather and lottery outcomes are independent.</p>
</div>
</section>
<section id="law-of-total-probability" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="law-of-total-probability">Law of Total Probability</h3>
<p>The <strong>Law of Total Probability</strong> states:</p>
<div class="callout-formula">
<p><strong>LAW OF TOTAL PROBABILITY</strong> <span class="math display">\[P(A)=P(A \cap B)+P(A\cap B^c)\]</span> which, using the multiplication rule, can also be written as <span class="math display">\[P(A)=P(A|B)P(B)+P(A|B^c)P(B^c)\]</span></p>
</div>
<p>The formula mainly states that if an event <span class="math inline">\(A\)</span> can occur in multiple mutually exclusive scenarios (or conditions), then the total probability of <span class="math inline">\(A\)</span> is the sum of its probabilities under each scenario, weighted by how often those scenarios occur. The Venn diagram helps us visualize the law of total probability.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="images/venn3.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:75.0%"></p>
</figure>
</div>
</div>
</div>
<p>The image shows how event <span class="math inline">\(A\)</span> can occur. Essentially, when <span class="math inline">\(B\)</span> occurs <span class="math inline">\(A\)</span> is possible in the left semicircle. When <span class="math inline">\(B^c\)</span>, then <span class="math inline">\(A\)</span> is possible in the right semicircle. The addition of both semicircles, complete set <span class="math inline">\(A\)</span>.</p>
<div class="callout-example">
<p><strong>Example:</strong> Consider the sets face cards and hearts. The entire set of hearts can be completed by taking face cards that are hearts, and non face cards (the complement of face cards) that are hearts.</p>
</div>
<p>The same idea extends to <strong>any</strong> number of scenarios. If <span class="math inline">\(B_1, B_2, \dots, B_k\)</span> are mutually exclusive and together cover the whole sample space, the total probability of <span class="math inline">\(A\)</span> is found by summing across all of them:</p>
<div class="callout-formula">
<p><strong>LAW OF TOTAL PROBABILITY (Several Events)</strong> <span class="math display">\[P(A)=\sum_{i=1}^{k} P(A \cap B_i)=\sum_{i=1}^{k} P(A|B_i)\,P(B_i)\]</span> where the events <span class="math inline">\(B_1, B_2, \dots, B_k\)</span> are mutually exclusive and exhaustive (they partition the sample space).</p>
</div>
<div class="callout-example">
<p><strong>Example:</strong> A factory makes a part on three machines. Machine 1 produces <span class="math inline">\(50\%\)</span> of the parts with a <span class="math inline">\(2\%\)</span> defect rate, Machine 2 produces <span class="math inline">\(30\%\)</span> with a <span class="math inline">\(3\%\)</span> defect rate, and Machine 3 produces <span class="math inline">\(20\%\)</span> with a <span class="math inline">\(5\%\)</span> defect rate. The overall probability that a randomly chosen part is defective is <span class="math display">\[P(D)=(0.50)(0.02)+(0.30)(0.03)+(0.20)(0.05)=0.029\]</span> so about <span class="math inline">\(2.9\%\)</span> of all parts are defective.</p>
</div>
</section>
<section id="bayes-theorem" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="bayes-theorem">Bayes’ Theorem</h3>
<p><strong>Bayes’ Theorem</strong> states:</p>
<div class="callout-formula">
<p><strong>BAYES’ THEOREM</strong> <span class="math display">\[P(A|B)= \frac{P(B|A)P(A)}{P(B)}\]</span></p>
</div>
<p>In essence, Bayes’ theorem is a way of updating probabilities in light of new evidence. The theorem tells us that the probability of an event A given that we have observed some evidence is equal to the prior probability (<span class="math inline">\(P(A)\)</span>) times a factor that measures the informativeness of the observed evidence <span class="math inline">\(P(B|A)/P(B)\)</span>.</p>
<div class="callout-example">
<p><strong>Example:</strong> Assume that a rare form of cancer affects 1% of the population. That is, 1 out of 100 people will likely be affected by it. There is a test for the cancer, but it is imperfect. In particular, if you don’t have cancer, the test says that you do 10% of the time (false positive rate). Also, if you do have cancer, it will tell you that you don’t have it 5% of the time. Let’s say you get tested, and your doctor calls you and says you have tested positive. How likely is it that you have this type of cancer?</p>
<p>We can use the Law of Total Probability and Bayes’ theorem to answer this question. Let’s first identify what we want to estimate. Since we need to figure out the likelihood of having cancer, given that we tested positive, we are looking for <span class="math inline">\(P(C|+)\)</span>. Now, we can set up Bayes’ rule to see what additional information we need to find our desired value. Bayes’ rule states:</p>
<p><span class="math display">\[P(C|+)= \frac{P(+|C)P(C)}{P(+)}\]</span> Since the problem does not provide the <span class="math inline">\(P(+)\)</span> we must estimate it with the Law of Total Probability, mainly:</p>
<p><span class="math display">\[P(+)=P(+|C)P(C)+P(+|NC)P(NC)=(0.95 \times 0.01+(0.1 \times 0.99)=0.1085\]</span> We can now use this probability to find our new belief that we have cancer:</p>
<p><span class="math display">\[P(C|+)= \frac{(0.95 \times 0.01) }{0.1085}=0.0875\]</span> In conclusion, if we before thought we had a <span class="math inline">\(1\%\)</span> chance of having the rare form of cancer, once we were told that we tested positive, we should update our belief to about <span class="math inline">\(8.75\%\)</span>.</p>
</div>
</section>
</section>
<section id="contingency-tables" class="level2" data-number="8.6">
<h2 data-number="8.6" class="anchored" data-anchor-id="contingency-tables"><span class="header-section-number">8.6</span> Contingency Tables</h2>
<p>A <strong>contingency table</strong> (or cross-tabulation) summarizes the relationship between two or events (or variables). It is particularly helpful when analyzing frequencies of events and there relationship to other events.</p>
<p>The contingency table below shows the frequency of event A and B occurring/not occurring.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="images/cont.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:75.0%"></p>
</figure>
</div>
</div>
</div>
<p>We can see that event A occurs 60 times and that event B occurs 40 times. Most importantly, we can also see how the two events are not mutually exclusive, since A and B occur 26 times. The table can be easily translated to probabilities, by divinding each entry by the total amount of outcomes (i.e., 100). We call the table that includes probabilities the <strong>joint probability table</strong>.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="images/joint.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:75.0%"></p>
</figure>
</div>
</div>
</div>
<p>In the middle of the table we have the joint probabilities or intersections of events (i.e., <span class="math inline">\(A \cap B\)</span>, <span class="math inline">\(A \cap B^c\)</span>, etc.). The values in the totals columns or rows are the probabilities of each event happening (i.e., <span class="math inline">\(P(A)\)</span>, <span class="math inline">\(P(B^c)\)</span>, etc.). We call these probabilities <strong>marginal probabilities</strong> since they reside at the margin of the table.</p>
</section>
<section id="counting-rules" class="level2" data-number="8.7">
<h2 data-number="8.7" class="anchored" data-anchor-id="counting-rules"><span class="header-section-number">8.7</span> Counting Rules</h2>
<p>Counting rules are useful in probability as they allow us to determine the number of ways events can occur without listing out every possibility. Essentially, they facilitate the enumeration of possible outcomes for large sets.</p>
<section id="the-fundamental-counting-principle" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="the-fundamental-counting-principle">The Fundamental Counting Principle</h3>
<p>The most basic counting rule — and the one all the others build on — is the <strong>Fundamental Counting Principle</strong> (also called the Multiplication Principle). It states that if a task is completed in separate stages, the total number of ways to complete it is the product of the number of choices available at each stage.</p>
<div class="callout-formula">
<p><strong>THE FUNDAMENTAL COUNTING PRINCIPLE</strong> <span class="math display">\[m_1 \times m_2 \times \dots \times m_k\]</span> where <span class="math inline">\(m_i\)</span> is the number of choices at stage <span class="math inline">\(i\)</span>, for a task made up of <span class="math inline">\(k\)</span> stages.</p>
</div>
<div class="callout-example">
<p><strong>Example:</strong> A restaurant offers <span class="math inline">\(3\)</span> appetizers, <span class="math inline">\(4\)</span> entrées, and <span class="math inline">\(2\)</span> desserts. The number of different three-course meals is <span class="math inline">\(3 \times 4 \times 2 = 24\)</span>.</p>
</div>
</section>
<section id="factorial" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="factorial">Factorial</h3>
<p>To illustrate the factorial, consider the number of ways that we can organize a group of three people (Ann, Beth, Charlie). The enumeration of all the possible orderings in this case is not that tedious and it can be shown in a table:</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th style="text-align: center;">Ordering</th>
<th style="text-align: center;">Order</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">1</td>
<td style="text-align: center;">(Ann, Beth, Charlie)</td>
</tr>
<tr class="even">
<td style="text-align: center;">2</td>
<td style="text-align: center;">(Ann, Charlie, Beth)</td>
</tr>
<tr class="odd">
<td style="text-align: center;">3</td>
<td style="text-align: center;">(Beth, Ann, Charlie)</td>
</tr>
<tr class="even">
<td style="text-align: center;">4</td>
<td style="text-align: center;">(Beth, Charlie, Ann)</td>
</tr>
<tr class="odd">
<td style="text-align: center;">5</td>
<td style="text-align: center;">(Charlie, Ann, Beth)</td>
</tr>
<tr class="even">
<td style="text-align: center;">6</td>
<td style="text-align: center;">(Charlie, Beth, Ann)</td>
</tr>
</tbody>
</table>
<p>The table shows that there are six possible ways to organize a group of three people. This is really just the Fundamental Counting Principle at work: there are <span class="math inline">\(3\)</span> choices for the first spot, then <span class="math inline">\(2\)</span> remaining choices for the second, and only <span class="math inline">\(1\)</span> left for the third, giving <span class="math inline">\(3 \times 2 \times 1 = 6\)</span>. The <strong>Factorial</strong> captures exactly this pattern — it counts how many ways a group of <span class="math inline">\(N\)</span> objects can be organized. Formally, we write:</p>
<div class="callout-formula">
<p><strong>THE FACTORIAL</strong> <span class="math display">\[Factorial=N!\]</span> where the operator <span class="math inline">\(!\)</span> means to take the product of all positive integers from <span class="math inline">\(N\)</span> down to <span class="math inline">\(1\)</span>. Note that <span class="math inline">\(0!\)</span> is equal to one.</p>
</div>
<p>If we then try to find in how many ways we can organize a group of three people, we can avoid enumeration by calculating <span class="math inline">\(3!=3 \times 2 \times 1=6\)</span>.</p>
<div class="callout-example">
<p><strong>Example:</strong> Let’s assume that a manager has locked down the first five batters in a given game, but is undecided on the batting order. The number of ways that he can organize the five batters is given by <span class="math inline">\(5!=5 \times 4 \times 3 \times 2 \times 1=120\)</span>.</p>
</div>
</section>
<section id="combinations" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="combinations">Combinations</h3>
<p>The <strong>Combination</strong> function counts the number of ways to choose <span class="math inline">\(x\)</span> objects from a total of <span class="math inline">\(n\)</span> objects. The order in which the <span class="math inline">\(x\)</span> objects are listed does not matter. If repetition is not allowed use:</p>
<div class="callout-formula">
<p><strong>COMBINATIONS (No Repetition)</strong> <span class="math display">\[C(n, x)= \frac{n!}{(n-x)!x!}\]</span></p>
</div>
<div class="callout-example">
<p><strong>Example:</strong> Let’s imagine visiting the Mexican restaurant Chipotle. We are choosing a bowl for lunch and we can choose from the following items: beans, chicken, rice, pico, guac, and beef. If we are only allowed to select four items out of the six, in how many ways can we construct a bowl? Below we use the combination formula to show that there are <span class="math inline">\(15\)</span> possible bowls. <span class="math display">\[C(6, 4)= \frac{6!}{(6-4)!4!}=\frac{6 \times 5}{2}=15\]</span></p>
</div>
<p>There are situations when we wish to count all possible combinations inclusive of repetition of elements. If repetition is allowed we use the following formula:</p>
<div class="callout-formula">
<p><strong>COMBINATIONS (With Repetition)</strong> <span class="math display">\[C(n+x-1,x)=\frac{(x+n-1)!}{(n-1)!x!}\]</span></p>
</div>
<div class="callout-example">
<p><strong>Example:</strong> Imagine you visit the ice cream store. You want a three scoop dish of ice cream. In how many ways can you choose your dish if the flavors are vanilla, chocolate, smores, brownie, and chips? Below we use the combination formula with repetition to show that the answer is <span class="math inline">\(35\)</span>. <span class="math display">\[C(7,3)=\frac{(5+3-1)!}{(5-1)!3!}= 7 \times 5=35\]</span></p>
</div>
</section>
<section id="permutations" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="permutations">Permutations</h3>
<p>The <strong>Permutation</strong> function also counts the number of ways to choose <span class="math inline">\(x\)</span> objects from a total of <span class="math inline">\(n\)</span> objects. However, the order in which the <span class="math inline">\(x\)</span> objects are listed does matter. Note that since order matters, the permutation will always have a higher number of possible outcomes relative to the combination. When repetition is not allowed, permutations can be counted by:</p>
<div class="callout-formula">
<p><strong>PERMUTATIONS (No Repetition)</strong> <span class="math display">\[P(n,x)= \frac{n!}{(n-x)!}\]</span></p>
</div>
<div class="callout-example">
<p><strong>Example:</strong> The Olympic medal finals for the 100 meters sprint has eight runners competing for three medals. How many medal podiums are possible? There are a total of <span class="math inline">\(336\)</span>. Below you can see the calculation. <span class="math display">\[P(8,3)= \frac{8!}{5!}= 8 \times 7 \times 6=336\]</span></p>
</div>
<p>As with combinations, there might be situations where we wish to count when repetition is allowed. If this is the case, use:</p>
<div class="callout-formula">
<p><strong>PERMUTATIONS (With Repetition)</strong> <span class="math display">\[P(n,x)=n^x\]</span></p>
</div>
<div class="callout-example">
<p><strong>Example:</strong> You are trying to guess the combination of a lock that has three possible numbers. Since there are 10 numbers to choose from, there are <span class="math inline">\(10^3=1000\)</span> possible permutations.</p>
</div>
</section>
</section>
<section id="probability-in-excel" class="level2" data-number="8.8">
<h2 data-number="8.8" class="anchored" data-anchor-id="probability-in-excel"><span class="header-section-number">8.8</span> Probability in Excel</h2>
<p>Excel has a collection of functions that make counting and probability calculations straightforward.</p>
<p><strong>Contingency tables:</strong> Use a <strong>PivotTable</strong> (<code>Insert → PivotTable</code>) to build a contingency table from raw data — place one variable in the Rows area, the other in the Columns area, and any field in the Values area as a count. To turn the counts into a joint probability table, use <code>Value Field Settings → Show Values As → % of Grand Total</code>. You can also count a specific combination of conditions directly with <code>=COUNTIFS(range1, criteria1, range2, criteria2)</code>.</p>
<p><strong>Factorial:</strong> The <code>=FACT(number)</code> function returns the factorial of a number. For example, <code>=FACT(5)</code> returns <span class="math inline">\(120\)</span>.</p>
<p><strong>Combinations:</strong> The <code>=COMBIN(number, number_chosen)</code> function counts the number of combinations without repetition. Use <code>=COMBINA(number, number_chosen)</code> when repetition is allowed.</p>
<p><strong>Permutations:</strong> The <code>=PERMUT(number, number_chosen)</code> function counts the number of permutations without repetition. Use <code>=PERMUTATIONA(number, number_chosen)</code> when repetition is allowed.</p>
</section>
<section id="excel-function-summary" class="level2" data-number="8.9">
<h2 data-number="8.9" class="anchored" data-anchor-id="excel-function-summary"><span class="header-section-number">8.9</span> Excel Function Summary</h2>
<p>Below is a list of the Excel functions used in this section:</p>
<ul>
<li><p><code>=COUNTIFS(range1, criteria1, ...)</code> counts the observations that satisfy several conditions at once, useful for building contingency tables.</p></li>
<li><p><code>=FACT(number)</code> returns the factorial of a number.</p></li>
<li><p><code>=COMBIN(number, number_chosen)</code> returns the number of combinations without repetition; <code>=COMBINA(number, number_chosen)</code> allows repetition.</p></li>
<li><p><code>=PERMUT(number, number_chosen)</code> returns the number of permutations without repetition; <code>=PERMUTATIONA(number, number_chosen)</code> allows repetition.</p></li>
</ul>
</section>
<section id="chapter-summary-cheat-sheet" class="level2" data-number="8.10">
<h2 data-number="8.10" class="anchored" data-anchor-id="chapter-summary-cheat-sheet"><span class="header-section-number">8.10</span> Chapter Summary Cheat Sheet</h2>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="images/Probability_Rules.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:100.0%"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="exercises" class="level2" data-number="8.11">
<h2 data-number="8.11" class="anchored" data-anchor-id="exercises"><span class="header-section-number">8.11</span> Exercises</h2>
<p>The following exercises will help you practice some probability concepts and formulas. In particular, the exercises work on:</p>
<ul>
<li><p>Calculating simple probabilities.</p></li>
<li><p>Applying probability rules.</p></li>
<li><p>Using counting rules.</p></li>
</ul>
<p>Answers are provided below. Try not to peak until you have a formulated your own answer and double checked your work for any mistakes.</p>
<section id="exercise-1" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="exercise-1">Exercise 1</h3>
<p>For the following exercises, make your calculations by hand and verify results with a calculator or Excel.</p>
<ol type="1">
<li>A sample space <span class="math inline">\(S\)</span> yields five equally likely events, <span class="math inline">\(A\)</span>, <span class="math inline">\(B\)</span>, <span class="math inline">\(C\)</span>, <span class="math inline">\(D\)</span>, and <span class="math inline">\(E\)</span>. Find <span class="math inline">\(P(D)\)</span>, <span class="math inline">\(P(B^c)\)</span>, and <span class="math inline">\(P(A \cup C \cup E)\)</span>.</li>
</ol>
<details>
<summary>
Answer
</summary>
<ul>
<li><span class="math inline">\(P(D)=1/5=0.2\)</span> since all events are equally likely.</li>
<li><span class="math inline">\(P(B^c)=4/5=0.8\)</span></li>
<li><span class="math inline">\(P(A \cup C \cup E)=P(A + C + E)=3/5=0.6\)</span>.</li>
</ul>
</details>
<ol start="2" type="1">
<li>Consider the roll of a die. Define <span class="math inline">\(A\)</span> as {1,2,3}, <span class="math inline">\(B\)</span> as {1,2,3,5,6}, <span class="math inline">\(C\)</span> as {4,6}, and <span class="math inline">\(D\)</span> as {4,5,6}. Are the events <span class="math inline">\(A\)</span> and <span class="math inline">\(B\)</span> mutually exclusive, exhaustive, both or none? What about events <span class="math inline">\(A\)</span> and <span class="math inline">\(D\)</span>?</li>
</ol>
<details>
<summary>
Answer
</summary>
<ul>
<li><em>Events</em> <span class="math inline">\(A\)</span> and <span class="math inline">\(B\)</span> are not mutually exclusive since they share some of the same elements.</li>
<li><em>The events are not exhaustive since the union of both doesn’t create the sample space.</em></li>
</ul>
</details>
<ol start="3" type="1">
<li>A recent study suggests that <span class="math inline">\(33.1\)</span>% of the adult U.S. population is overweight and <span class="math inline">\(35.7\)</span>% obese. What is the probability that a randomly selected adult in the U.S. is either obese or overweight? Are the events mutually exclusive and exhaustive? What is the probability that their weight is normal?</li>
</ol>
<details>
<summary>
Answer
</summary>
<ul>
<li><em>The probability is</em> <span class="math inline">\(68.8\)</span>%.</li>
<li><em>The events are mutually exclusive. If someone is classified as obese, the person is not classified again as overweight.</em></li>
<li><em>The events are not exhaustive since there are people in the U.S. that have a normal weight.</em></li>
<li><em>The probability that the person drawn has normal weight is</em> <span class="math inline">\(31.2\)</span>%.</li>
</ul>
</details>
</section>
<section id="exercise-2" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="exercise-2">Exercise 2</h3>
<p>For the following exercises, make your calculations by hand and verify results with a calculator or Excel.</p>
<ol type="1">
<li>Let <span class="math inline">\(P(A)=0.65\)</span>, <span class="math inline">\(P(B)=0.3\)</span>, and <span class="math inline">\(P(A|B)=0.45\)</span>. Calculate <span class="math inline">\(P(A \cap B)\)</span>, <span class="math inline">\(P(A \cup B)\)</span>, and <span class="math inline">\(P(B|A)\)</span>.</li>
</ol>
<details>
<summary>
Answer
</summary>
<p><em>From the multiplication rule,</em> <span class="math display">\[P(A|B)*P(B)=P(A \cap B)\]</span></p>
<p><em>substituting values yields:</em> <span class="math display">\[P(A \cap B)=0.45*0.3=0.135\]</span> <em>From the addition rule,</em> <span class="math display">\[P(A \cup B)=P(A)+P(B)-P(A \cap B)\]</span> <em>substituting yields:</em> <span class="math display">\[P(A \cup B)=0.65+0.3-0.135=0.815\]</span> <em>From the multiplication rule once again,</em> <span class="math display">\[P(B|A)=\frac{P(A \cap B)}{P(A)}\]</span> <em>substituting values yields,</em> <span class="math display">\[P(B|A)=0.135/0.65=0.2076923\]</span></p>
</details>
<ol start="2" type="1">
<li>Let <span class="math inline">\(P(A)=0.4\)</span>, <span class="math inline">\(P(B)=0.5\)</span>, and <span class="math inline">\(P(A^c \cap B^c)=0.24\)</span>. Calculate <span class="math inline">\(P(A^c|B^c)\)</span>, <span class="math inline">\(P(A^c \cup B^c)\)</span>, and <span class="math inline">\(P(A \cup B)\)</span>.</li>
</ol>
<details>
<summary>
Answer
</summary>
<p><em>From the complement rule we have that</em> <span class="math inline">\(P(A^c)=0.6\)</span> and <span class="math inline">\(P(B^c)=0.5\)</span>.<br>
<em>Using the multiplication rule,</em> <span class="math display">\[P(A^c|B^c)=\frac{P(A^c \cap B^c)}{P(B^c)}\]</span> <em>substituting yields:</em> <span class="math display">\[P(A^c|B^c)=0.24/0.5=0.48\]</span> <em>From the addition rule,</em> <span class="math display">\[P(A^c \cup B^c)=P(A^c)+P(B^c)-P(A^c \cap B^c)\]</span> <em>substituting yields:</em> <span class="math display">\[P(A^c \cup B^c)=0.6+0.5-0.24=0.86\]</span> <em>The event that has no elements of</em> <span class="math inline">\(A\)</span> or <span class="math inline">\(B\)</span> is given by <span class="math inline">\(P(A^c \cap B^c)\)</span>. Therefore <span class="math inline">\(P(A \cup B)=1-0.24=0.76\)</span> has all the elements of A and B.</p>
</details>
<ol start="3" type="1">
<li>Stock <span class="math inline">\(A\)</span> will rise in price with a probability of <span class="math inline">\(0.4\)</span>, stock <span class="math inline">\(B\)</span> will rise with a probability of <span class="math inline">\(0.6\)</span>. If stock <span class="math inline">\(B\)</span> rises in price, then <span class="math inline">\(A\)</span> will also rise with a probability of <span class="math inline">\(0.5\)</span>. What is the probability that at least one of the stocks will rise in price? Prove that events <span class="math inline">\(A\)</span> and <span class="math inline">\(B\)</span> are (are not) mutually exclusive (independent).</li>
</ol>
<details>
<summary>
Answer
</summary>
<p><em>In short, the problem states</em> <span class="math inline">\(P(A)=0.4\)</span>, <span class="math inline">\(P(B)=0.6\)</span>, and <span class="math inline">\(P(A|B)=0.5\)</span>. Where <span class="math inline">\(A\)</span> and <span class="math inline">\(B\)</span> are events of stocks rising in price. The question asks for: <span class="math display">\[P(A \cup B)=P(A)+P(B)-P(A \cap B)\]</span> <em>Using the multiplication rule,</em> <span class="math display">\[P(A \cap B)=0.5*0.6=0.3\]</span> <em>Hence,</em> <span class="math display">\[P(A \cup B)=0.4+0.6-0.3=0.7\]</span> <em>The events are not mutually exclusive since</em> <span class="math inline">\(P(A \cap B)=0.3 \neq 0\)</span>. The events are also not independent since <span class="math inline">\(P(A|B)=0.5 \neq 0.4=P(A)\)</span>.</p>
</details>
</section>
<section id="exercise-3" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="exercise-3">Exercise 3</h3>
<ol type="1">
<li>Create a joint probability table from the contingency table below. Find <span class="math inline">\(P(A)\)</span>, <span class="math inline">\(P(A \cap B)\)</span>, <span class="math inline">\(P(A|B)\)</span>, and <span class="math inline">\(P(B|A^c)\)</span>. Determine whether the events are independent or mutually exclusive.</li>
</ol>
<table class="caption-top table">
<tbody>
<tr class="odd">
<td></td>
<td><span class="math inline">\(B\)</span></td>
<td><span class="math inline">\(B^c\)</span></td>
</tr>
<tr class="even">
<td><span class="math inline">\(A\)</span></td>
<td>26</td>
<td>34</td>
</tr>
<tr class="odd">
<td><span class="math inline">\(A^c\)</span></td>
<td>14</td>
<td>26</td>
</tr>
</tbody>
</table>
<details>
<summary>
Answer
</summary>
<p><em>Below is the joint probability table. The</em> <span class="math inline">\(P(A)=0.26+0.34=0.6\)</span>, <span class="math inline">\(P(A \cap B)=0.26\)</span>, <span class="math inline">\(P(A|B)=0.26/0.4=0.65\)</span>, and <span class="math inline">\(P(B|A^c)=0.14/0.4=0.35\)</span>. Events <span class="math inline">\(A\)</span> and <span class="math inline">\(B\)</span> are not independent since <span class="math inline">\(P(A) \neq P(A|B)\)</span>. The events are not mutually exclusive since <span class="math inline">\(P(A \cap B)=0.26 \neq 0\)</span>.</p>
<table class="caption-top table">
<tbody>
<tr class="odd">
<td></td>
<td><span class="math inline">\(B\)</span></td>
<td><span class="math inline">\(B^c\)</span></td>
<td>Total</td>
</tr>
<tr class="even">
<td><span class="math inline">\(A\)</span></td>
<td>0.26</td>
<td>0.34</td>
<td>0.6</td>
</tr>
<tr class="odd">
<td><span class="math inline">\(A^c\)</span></td>
<td>0.14</td>
<td>0.26</td>
<td>0.4</td>
</tr>
<tr class="even">
<td>Total</td>
<td>0.4</td>
<td>0.6</td>
<td>1</td>
</tr>
</tbody>
</table>
</details>
</section>
<section id="exercise-4" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="exercise-4">Exercise 4</h3>
<p>You will need the <strong>Crash</strong> data set to answer this question. The data shows information on several car crashes. Specifically, whether the crash was Head-On or Not Head-On and whether there was Daylight or No Daylight. You can download it here:</p>
<p><a href="Crash.xlsx" class="btn btn-success"><i class="fa-solid fa-file-excel" aria-label="file-excel"></i> Download Data</a></p>
<ol type="1">
<li>Create a contingency table.</li>
</ol>
<details>
<summary>
Answer
</summary>
<p><em>The contingency table below shows the counts for each combination of Crash Type and Light Condition:</em></p>
<table class="caption-top table">
<thead>
<tr class="header">
<th style="text-align: center;"></th>
<th style="text-align: center;">Daylight</th>
<th style="text-align: center;">Not Daylight</th>
<th style="text-align: center;">Total</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">Head-on</td>
<td style="text-align: center;">166</td>
<td style="text-align: center;">108</td>
<td style="text-align: center;">274</td>
</tr>
<tr class="even">
<td style="text-align: center;">Not Head-On</td>
<td style="text-align: center;">3258</td>
<td style="text-align: center;">1326</td>
<td style="text-align: center;">4584</td>
</tr>
<tr class="odd">
<td style="text-align: center;">Total</td>
<td style="text-align: center;">3424</td>
<td style="text-align: center;">1434</td>
<td style="text-align: center;">4858</td>
</tr>
</tbody>
</table>
<p><em>In Excel, build a PivotTable: drag <code>Crash Type</code> to the Rows area, <code>Light Condition</code> to the Columns area, and either field to the Values area as a Count. To turn the counts into a joint probability table, use <code>Value Field Settings → Show Values As → % of Grand Total</code>. You can also count any single cell directly. Assuming <code>Crash Type</code> is in column B and <code>Light Condition</code> in column C:</em></p>
<ul>
<li><code>=COUNTIFS(B:B, "Head-on", C:C, "Daylight")</code> → <span class="math inline">\(166\)</span></li>
</ul>
</details>
<ol start="2" type="1">
<li>Find the probability that a) a car crash is Head-On, b) a car crash is in daylight c) a car crash is Head-On given that there is daylight.</li>
</ol>
<details>
<summary>
Answer
</summary>
<p><em>a) The probability of a Head-On crash is:</em></p>
<p><span class="math display">\[P(\text{Head-on})=\frac{166+108}{4858}=\frac{274}{4858}=0.056\]</span></p>
<p><em>b) The probability that the crash is in daylight is:</em></p>
<p><span class="math display">\[P(\text{Daylight})=\frac{166+3258}{4858}=\frac{3424}{4858}=0.70\]</span></p>
<p><em>c) The probability that a crash is Head-On given daylight is:</em></p>
<p><span class="math display">\[P(\text{Head-on}\mid\text{Daylight})=\frac{P(\text{Head-on}\cap\text{Daylight})}{P(\text{Daylight})}=\frac{166}{3424}=0.048\]</span></p>
<p><em>In Excel these follow from the PivotTable counts. For example, part a) is <code>=COUNTIF(B:B,"Head-on") / COUNTA(B2:B4859)</code>.</em></p>
</details>
<ol start="3" type="1">
<li>Show that Crashes and Light are dependent.</li>
</ol>
<details>
<summary>
Answer
</summary>
<p><em>The two variables are dependent since</em> <span class="math inline">\(P(\text{Head-on}\mid\text{Daylight}) \neq P(\text{Head-on})\)</span>, that is <span class="math inline">\(0.048 \neq 0.056\)</span>.</p>
</details>
</section>
<section id="exercise-5" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="exercise-5">Exercise 5</h3>
<ol type="1">
<li>Use Bayes’ Theorem in the following question. Let <span class="math inline">\(P(A)=0.7\)</span>, <span class="math inline">\(P(B|A)=0.55\)</span>, and <span class="math inline">\(P(B|A^c)=0.10\)</span>. Find <span class="math inline">\(P(A^c)\)</span>, <span class="math inline">\(P(A \cap B)\)</span>, <span class="math inline">\(P(A^c \cap B)\)</span>, <span class="math inline">\(P(B)\)</span>, and <span class="math inline">\(P(A|B)\)</span>.</li>
</ol>
<details>
<summary>
Answer
</summary>
<p><span class="math inline">\(P(A^c)=1-P(A)=1-0.7=0.3\)</span>, <span class="math inline">\(P(A \cap B)=𝑃(𝐵|𝐴)𝑃(𝐴) = 0.55(0.70) = 0.385\)</span>, <span class="math inline">\(P(A^c \cap B)=𝑃(B|A^c)𝑃(A^c) = 0.10(0.30) = 0.03\)</span>, <span class="math inline">\(P(B)= 𝑃(A \cap B) + 𝑃(𝐴^c \cap 𝐵) = 0.385 + 0.03 = 0.415\)</span>, and <span class="math inline">\(P(A|B)= \frac{𝑃(A \cap B)}{P(B)}=0.385/0.415=0.9277\)</span>.</p>
</details>
<ol start="2" type="1">
<li>Some find tutors helpful when taking a course. Julia has a 40% chance to fail a course if she does not have a tutor. With a tutor, the probability of failing is only 10%. There is a 50% chance that Julia finds an available tutor. What is the probability that Julia will fail the course? If she ends up failing the course, what is the probability that she had a tutor?</li>
</ol>
<details>
<summary>
Answer
</summary>
<p><em>Let the event of failing be</em> <span class="math inline">\(F\)</span>, the event of not failing be <span class="math inline">\(NF\)</span>, the event of having a tutor be <span class="math inline">\(T\)</span>, and the event of not having a tutor be <span class="math inline">\(NT\)</span>. The probability of failing the course is <span class="math inline">\(0.25\)</span>. <span class="math inline">\((𝐹) = 𝑃(𝐹 \cap 𝑇) + 𝑃(𝐹 \cap 𝑇^c) = 𝑃(𝐹|𝑇)𝑃(𝑇) + 𝑃(𝐹|𝑇^c)𝑃(𝑇^c) = 0.10(0.50) + 0.40(0.50) = 0.05 + 0.20 = 0.25\)</span> The probability of not having a tutor, given that she failed the course is <span class="math inline">\(0.2\)</span>. <span class="math inline">\(P(𝑇|𝐹) = \frac{𝑃(𝐹\cap𝑇)}{𝑃(𝐹\cap𝑇)+𝑃(𝐹 \cap𝑇^c)}= 0.05/0.25 = 0.20\)</span>.</p>
</details>
</section>
<section id="exercise-6" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="exercise-6">Exercise 6</h3>
<ol type="1">
<li>Calculate the following values and verify your results using Excel. a) 3!, b) 4!, c) <span class="math inline">\(C_6^8\)</span>, d) <span class="math inline">\(P_6^8\)</span>.</li>
</ol>
<details>
<summary>
Answer
</summary>
<p><span class="math inline">\(3!=3 \times 2 \times 1=6\)</span>, <span class="math inline">\(4!=4 \times 3 \times 2 \times 1=24\)</span>, <span class="math inline">\(C_6^8=28\)</span>, and <span class="math inline">\(P_6^8=20{,}160\)</span>.</p>
<p><em>In Excel:</em></p>
<ul>
<li><code>=FACT(3)</code> → <span class="math inline">\(6\)</span></li>
<li><code>=FACT(4)</code> → <span class="math inline">\(24\)</span></li>
<li><code>=COMBIN(8, 6)</code> → <span class="math inline">\(28\)</span></li>
<li><code>=PERMUT(8, 6)</code> → <span class="math inline">\(20{,}160\)</span></li>
</ul>
</details>
<ol start="2" type="1">
<li>There are 10 players in a local basketball team. If we chose 5 players to randomly start a game, in how many ways can we select the five players if order doesn’t matter? What if order matters?</li>
</ol>
<details>
<summary>
Answer
</summary>
<p><em>If order doesn’t matter, there are</em> <span class="math inline">\(252\)</span> ways. If order matters, then there are <span class="math inline">\(30{,}240\)</span> ways.</p>
<p><em>In Excel:</em></p>
<ul>
<li><code>=COMBIN(10, 5)</code> → <span class="math inline">\(252\)</span></li>
<li><code>=PERMUT(10, 5)</code> → <span class="math inline">\(30{,}240\)</span></li>
</ul>
</details>


</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    // For code content inside modals, clipBoardJS needs to be initialized with a container option
    // TODO: Check when it could be a function (https://github.com/zenorocha/clipboard.js/issues/860)
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./RegressionII.html" class="pagination-link" aria-label="Regression II">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Regression II</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./ProbabilityII.html" class="pagination-link" aria-label="Probability II">
        <span class="nav-page-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Probability II</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
<p>Business Statistics by J. Alejandro Gelves.</p>
</div>   
    <div class="nav-footer-center">
      &nbsp;
    </div>
    <div class="nav-footer-right">
<p>This book was built with <a href="https://quarto.org/">Quarto</a>.</p>
</div>
  </div>
</footer>




</body></html>