<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.6.32">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>7&nbsp; Regression II – Business Statistics</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./ProbabilityI.html" rel="next">
<link href="./RegressionI.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-2486e1f0a3ee9ee1fc393803a1361cdb.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-9904b5196d746cb5bc47063911474b57.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<link href="site_libs/quarto-contrib/fontawesome6-6.7.2/all.min.css" rel="stylesheet">
<link href="site_libs/quarto-contrib/fontawesome6-6.7.2/latex-fontsize.css" rel="stylesheet">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<!-- Google tag (gtag.js) -->
<script async="" src="https://www.googletagmanager.com/gtag/js?id=G-FWC3RCL4BF"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'G-FWC3RCL4BF');
</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="nav-sidebar floating">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./RegressionII.html"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Regression II</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">Business Statistics</a> 
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Introduction</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./DescriptiveI.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Descriptive Stats I</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./DescriptiveII.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Descriptive Stats II</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./DescriptiveIII.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Descriptive Statistics III</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./DescriptiveIV.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Descriptive Stats IV</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./DescriptiveV.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Descriptive Stats V</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./RegressionI.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Regression I</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./RegressionII.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Regression II</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./ProbabilityI.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Probability I</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./ProbabilityII.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Probability II</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./ProbabilityIII.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Probability III</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./InferenceI.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Inference I</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./InferenceII.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Inference II</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./InferenceIII.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">Inference III</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./InfReg.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">14</span>&nbsp; <span class="chapter-title">Regression and Inference</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Excel Basics.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">15</span>&nbsp; <span class="chapter-title">Excel Basics</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./references.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">References</span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#the-regression-line" id="toc-the-regression-line" class="nav-link active" data-scroll-target="#the-regression-line"><span class="header-section-number">7.1</span> The Regression Line</a></li>
  <li><a href="#measures-of-goodness-of-fit" id="toc-measures-of-goodness-of-fit" class="nav-link" data-scroll-target="#measures-of-goodness-of-fit"><span class="header-section-number">7.2</span> Measures of Goodness of Fit</a>
  <ul class="collapse">
  <li><a href="#coefficient-of-determination" id="toc-coefficient-of-determination" class="nav-link" data-scroll-target="#coefficient-of-determination">Coefficient of Determination</a></li>
  </ul></li>
  <li><a href="#multiple-regression" id="toc-multiple-regression" class="nav-link" data-scroll-target="#multiple-regression"><span class="header-section-number">7.3</span> Multiple Regression</a>
  <ul class="collapse">
  <li><a href="#anova" id="toc-anova" class="nav-link" data-scroll-target="#anova">Anova</a></li>
  <li><a href="#adjusted-r2" id="toc-adjusted-r2" class="nav-link" data-scroll-target="#adjusted-r2">Adjusted <span class="math inline">\(R^2\)</span></a></li>
  <li><a href="#residual-standard-error" id="toc-residual-standard-error" class="nav-link" data-scroll-target="#residual-standard-error">Residual Standard Error</a></li>
  </ul></li>
  <li><a href="#regression-in-excel" id="toc-regression-in-excel" class="nav-link" data-scroll-target="#regression-in-excel"><span class="header-section-number">7.4</span> Regression in Excel</a></li>
  <li><a href="#excel-function-summary" id="toc-excel-function-summary" class="nav-link" data-scroll-target="#excel-function-summary"><span class="header-section-number">7.5</span> Excel Function Summary</a></li>
  <li><a href="#exercises" id="toc-exercises" class="nav-link" data-scroll-target="#exercises"><span class="header-section-number">7.6</span> Exercises</a>
  <ul class="collapse">
  <li><a href="#exercise-1" id="toc-exercise-1" class="nav-link" data-scroll-target="#exercise-1">Exercise 1</a></li>
  <li><a href="#exercise-2" id="toc-exercise-2" class="nav-link" data-scroll-target="#exercise-2">Exercise 2</a></li>
  <li><a href="#exercise-3" id="toc-exercise-3" class="nav-link" data-scroll-target="#exercise-3">Exercise 3</a></li>
  <li><a href="#exercise-4" id="toc-exercise-4" class="nav-link" data-scroll-target="#exercise-4">Exercise 4</a></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Regression II</span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<style>
details {
  background-color: #F8F9FA;
  padding: 5px;
  border: 1px solid #ddd;
  border-radius: 5px;
  margin: 10px 0;
}
details summary {
  cursor: pointer;
}
</style>
<p>Quantifying relationships between variables is an important skill in business analytics. The regression line, representing the best linear fit between two variables, enables businesses to make predictions, identify trends, and optimize strategies using data-driven insights. Understanding how to calculate and interpret a regression line provides the foundation for analyzing business relationships, such as the effect of advertising on sales or customer satisfaction on revenue. Below, we delve into generating and analyzing a regression line.</p>
<section id="the-regression-line" class="level2" data-number="7.1">
<h2 data-number="7.1" class="anchored" data-anchor-id="the-regression-line"><span class="header-section-number">7.1</span> The Regression Line</h2>
<p>The regression line is calculated to minimize the average distance (or errors) between the line and the observed data points. It is defined by two key components: a <strong>slope</strong> (<span class="math inline">\(\hat{\beta}\)</span>) and an <strong>intercept</strong> (<span class="math inline">\(\hat{\alpha}\)</span>). Mathematically, the regression line is expressed as:</p>
<div class="callout-formula">
<p><strong>THE REGRESSION LINE</strong> <span class="math display">\[\hat{y_i}=\hat{\alpha}+\hat{\beta}x_i\]</span> where <span class="math inline">\(\hat{y_i}\)</span> are the predicted values of <span class="math inline">\(y\)</span> given <span class="math inline">\(x_i\)</span>, <span class="math inline">\(\hat{\alpha}\)</span> is the intercept, and <span class="math inline">\(\hat{\beta}\)</span> is the slope.</p>
</div>
<p>The <strong>slope</strong> determines the steepness of the line and quantifies how much a unit increase in <span class="math inline">\(x\)</span> changes <span class="math inline">\(y\)</span> on average. It is calculated using the covariance between <span class="math inline">\(y\)</span> and <span class="math inline">\(x\)</span> and the variance of <span class="math inline">\(x\)</span>:</p>
<div class="callout-formula">
<p><strong>THE SLOPE</strong> <span class="math display">\[\hat{\beta}= \frac{s_{xy}}{s_{x}^2}\]</span> where <span class="math inline">\(s_{xy}\)</span> is the sample covariance between <span class="math inline">\(x\)</span> and <span class="math inline">\(y\)</span>, and <span class="math inline">\(s_x^2\)</span> is the sample variance of <span class="math inline">\(x\)</span>.</p>
</div>
<p>The <strong>intercept</strong> determines where the line crosses the <span class="math inline">\(y\)</span> axis — the predicted value of <span class="math inline">\(y\)</span> when <span class="math inline">\(x\)</span> is zero. Once the slope is estimated, the intercept is calculated by:</p>
<div class="callout-formula">
<p><strong>THE INTERCEPT</strong> <span class="math display">\[\hat{\alpha}=\bar{y}-\hat{\beta}\bar{x}\]</span> where <span class="math inline">\(\bar{y}\)</span> is the mean of <span class="math inline">\(y\)</span> and <span class="math inline">\(\bar{x}\)</span> is the mean of <span class="math inline">\(x\)</span>.</p>
</div>
<div class="callout-example">
<p><strong>Example:</strong> Let’s examine a data set on Price and Advertisement. In general, one expects that when a company advertises, it can convince consumers to pay more for their product. Below is the data:</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th style="text-align: center;">Advertisement (x)</th>
<th style="text-align: center;">Price (y)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">2</td>
<td style="text-align: center;">7</td>
</tr>
<tr class="even">
<td style="text-align: center;">1</td>
<td style="text-align: center;">3</td>
</tr>
<tr class="odd">
<td style="text-align: center;">3</td>
<td style="text-align: center;">8</td>
</tr>
<tr class="even">
<td style="text-align: center;">4</td>
<td style="text-align: center;">10</td>
</tr>
</tbody>
</table>
<p>The data shows a clear direct relationship between advertisement and price. Regression allows us to answer two key questions:</p>
<ol type="1">
<li><strong>Effectiveness:</strong> How much can we increase the price for every additional dollar spent on advertisement?</li>
<li><strong>Prediction:</strong> What is the predicted price if we have a budget of <span class="math inline">\(6\)</span> for advertisement?</li>
</ol>
<p><strong>Step 1 — Calculate the slope:</strong> Given that the covariance is <span class="math inline">\(s_{xy}=3.67\)</span> and the variance of <span class="math inline">\(x\)</span> is <span class="math inline">\(s_x^2=1.67\)</span>:</p>
<p><span class="math display">\[\hat{\beta}= \frac{3.67}{1.67}=2.2\]</span></p>
<p>For every additional dollar spent on advertisement, price increases by <span class="math inline">\(2.2\)</span> on average.</p>
<p><strong>Step 2 — Calculate the intercept:</strong> Since <span class="math inline">\(\bar{x}=2.5\)</span> and <span class="math inline">\(\bar{y}=7\)</span>:</p>
<p><span class="math display">\[\hat{\alpha}=7-2.2(2.5)=1.5\]</span></p>
<p>If we do not advertise, the predicted price is <span class="math inline">\(1.5\)</span>.</p>
<p><strong>Step 3 — Write the regression line:</strong></p>
<p><span class="math display">\[\hat{y_i}=1.5+2.2x_i\]</span></p>
<p><strong>Step 4 — Make a prediction:</strong> With an advertisement budget of <span class="math inline">\(6\)</span>:</p>
<p><span class="math display">\[\hat{y_i}=1.5+2.2(6)=14.7\]</span></p>
<p>In conclusion, for every dollar spent on advertisement the price increases by <span class="math inline">\(2.2\)</span>, and with a budget of <span class="math inline">\(6\)</span> the predicted price is <span class="math inline">\(14.7\)</span>.</p>
</div>
</section>
<section id="measures-of-goodness-of-fit" class="level2" data-number="7.2">
<h2 data-number="7.2" class="anchored" data-anchor-id="measures-of-goodness-of-fit"><span class="header-section-number">7.2</span> Measures of Goodness of Fit</h2>
<p>When analyzing the effectiveness of a regression model, it is crucial to assess how well the model fits the data. Below we revisit the coefficient of determination <span class="math inline">\(R^2\)</span> and introduce additional measures.</p>
<section id="coefficient-of-determination" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="coefficient-of-determination">Coefficient of Determination</h3>
<p>The <strong>coefficient of determination</strong> or <span class="math inline">\(R^2\)</span> is the percent of the variation in <span class="math inline">\(y\)</span> that is explained by changes in <span class="math inline">\(x\)</span>. The higher the <span class="math inline">\(R^2\)</span> the better the explanatory power of the model.</p>
<div class="callout-formula">
<p><strong>THE COEFFICIENT OF DETERMINATION</strong> <span class="math display">\[R^2=\frac{SSR}{SST}\]</span></p>
<p>where:</p>
<ul>
<li><span class="math inline">\(SST = \sum(y_i-\bar{y})^2\)</span> — total variation in <span class="math inline">\(y\)</span></li>
<li><span class="math inline">\(SSR = \sum(\hat{y_i}-\bar{y})^2\)</span> — variation explained by the model</li>
<li><span class="math inline">\(SSE = \sum(y_i-\hat{y_i})^2\)</span> — variation unexplained by the model</li>
<li><span class="math inline">\(SST = SSR + SSE\)</span></li>
</ul>
<p><span class="math inline">\(R^2\)</span> is always between <span class="math inline">\([0,1]\)</span>.</p>
</div>
<div class="callout-example">
<p><strong>Example:</strong> Consider data on the Weight (<span class="math inline">\(y\)</span>) and Exercise (<span class="math inline">\(x\)</span>) of a particular person:</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th style="text-align: center;">Weight (y)</th>
<th style="text-align: center;">Exercise (x)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">165</td>
<td style="text-align: center;">45</td>
</tr>
<tr class="even">
<td style="text-align: center;">170</td>
<td style="text-align: center;">10</td>
</tr>
<tr class="odd">
<td style="text-align: center;">168</td>
<td style="text-align: center;">25</td>
</tr>
<tr class="even">
<td style="text-align: center;">164</td>
<td style="text-align: center;">30</td>
</tr>
<tr class="odd">
<td style="text-align: center;">165</td>
<td style="text-align: center;">40</td>
</tr>
</tbody>
</table>
<p>If we used only the mean <span class="math inline">\(\bar{y}=166.4\)</span> as our prediction, the total squared error would be:</p>
<p><span class="math display">\[SST=(-1.4)^2+(3.6)^2+(1.6)^2+(-2.4)^2+(-1.4)^2=25.2\]</span></p>
<p>Using the regression line reduces these errors. The mistakes made by the regression line are quantified by:</p>
<p><span class="math display">\[SSE=0.81+0.29+0.69+5.76+0.02=7.57\]</span></p>
<p>The improvement gained by using regression over the mean is:</p>
<p><span class="math display">\[SSR=5.29+9.4+0.59+0+2.35=17.63\]</span></p>
<p>Hence the coefficient of determination is:</p>
<p><span class="math display">\[R^2=\frac{SSR}{SST}=\frac{17.63}{25.2}\approx0.70\]</span></p>
<p>The regression line explains about <span class="math inline">\(70\%\)</span> of the variation in Weight using Exercise.</p>
</div>
</section>
</section>
<section id="multiple-regression" class="level2" data-number="7.3">
<h2 data-number="7.3" class="anchored" data-anchor-id="multiple-regression"><span class="header-section-number">7.3</span> Multiple Regression</h2>
<p>If we were to predict weight we could use several other variables to get a better prediction. <strong>Multiple regression</strong> is a technique used to predict a variable using more than one independent variable.</p>
<div class="callout-formula">
<p><strong>THE MULTIPLE REGRESSION LINE</strong> <span class="math display">\[\hat{y_i}=\hat{\beta_0}+\hat{\beta_1}x_1+\hat{\beta_2}x_2+...+\hat{\beta_k}x_k\]</span> where <span class="math inline">\(k\)</span> is the total number of independent variables included in the model.</p>
</div>
<div class="callout-example">
<p><strong>Example:</strong> Let’s consider an additional variable in our Weight and Exercise example. The table below includes information on Calories (<span class="math inline">\(z\)</span>):</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th style="text-align: center;">Weight (y)</th>
<th style="text-align: center;">Exercise (x)</th>
<th style="text-align: center;">Calories (z)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">165</td>
<td style="text-align: center;">45</td>
<td style="text-align: center;">1200</td>
</tr>
<tr class="even">
<td style="text-align: center;">170</td>
<td style="text-align: center;">10</td>
<td style="text-align: center;">1260</td>
</tr>
<tr class="odd">
<td style="text-align: center;">168</td>
<td style="text-align: center;">25</td>
<td style="text-align: center;">1220</td>
</tr>
<tr class="even">
<td style="text-align: center;">164</td>
<td style="text-align: center;">30</td>
<td style="text-align: center;">1180</td>
</tr>
<tr class="odd">
<td style="text-align: center;">165</td>
<td style="text-align: center;">40</td>
<td style="text-align: center;">1190</td>
</tr>
</tbody>
</table>
<p>The multiple regression line estimated by computer software is:</p>
<p><span class="math display">\[\hat{y_i}=83.96-0.025x+0.069z\]</span></p>
<p>Two conclusions follow from this result. First, as exercise increases weight tends to go down, while more calories increases weight. Second, reducing calorie consumption by <span class="math inline">\(1\)</span> unit decreases weight by <span class="math inline">\(0.069\)</span> pounds, whereas one additional minute of exercise only reduces weight by <span class="math inline">\(0.025\)</span> pounds — making calorie reduction more effective per unit.</p>
</div>
<section id="anova" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="anova">Anova</h3>
<p>The Anova table helps us understand how well each variable in our regression model explains the dependent variable. It decomposes the <span class="math inline">\(SSR\)</span> by variable and tracks the remaining errors.</p>
<div class="callout-example">
<p><strong>Example:</strong> For the Weight, Exercise, and Calories regression, the Anova table is:</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th style="text-align: center;">Source</th>
<th style="text-align: center;">Sum Squares</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">x</td>
<td style="text-align: center;">17.63</td>
</tr>
<tr class="even">
<td style="text-align: center;">z</td>
<td style="text-align: center;">6.55</td>
</tr>
<tr class="odd">
<td style="text-align: center;">Residuals</td>
<td style="text-align: center;">1.01</td>
</tr>
</tbody>
</table>
<p>Exercise explains <span class="math inline">\(17.63\)</span> of the total variation. Adding Calories reduces the remaining unexplained variation by another <span class="math inline">\(6.55\)</span>, bringing the total <span class="math inline">\(SSR\)</span> to <span class="math inline">\(24.18\)</span> and the <span class="math inline">\(SSE\)</span> down to <span class="math inline">\(1.01\)</span>. The <span class="math inline">\(R^2\)</span> increases from <span class="math inline">\(0.70\)</span> to:</p>
<p><span class="math display">\[R^2=\frac{17.63+6.55}{25.2}=0.96\]</span></p>
</div>
</section>
<section id="adjusted-r2" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="adjusted-r2">Adjusted <span class="math inline">\(R^2\)</span></h3>
<p>The <strong>adjusted</strong> <span class="math inline">\(R^2\)</span> penalizes a model for including additional explanatory variables, preventing artificial inflation of <span class="math inline">\(R^2\)</span>.</p>
<div class="callout-formula">
<p><strong>THE ADJUSTED <span class="math inline">\(R^2\)</span></strong> <span class="math display">\[\bar{R}^2=1-(1-R^2)\frac{n-1}{n-k-1}\]</span> where <span class="math inline">\(k\)</span> is the number of explanatory variables and <span class="math inline">\(n\)</span> is the sample size.</p>
</div>
<div class="callout-example">
<p><strong>Example:</strong> For the Weight example with both Exercise and Calories (<span class="math inline">\(k=2\)</span>, <span class="math inline">\(n=5\)</span>, <span class="math inline">\(R^2=0.96\)</span>):</p>
<p><span class="math display">\[\bar{R}^2=1-(1-0.96)\frac{5-1}{5-2-1}=0.92\]</span></p>
</div>
</section>
<section id="residual-standard-error" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="residual-standard-error">Residual Standard Error</h3>
<p>The <strong>Residual Standard Error</strong> estimates the average dispersion of the data points around the regression line.</p>
<div class="callout-formula">
<p><strong>THE RESIDUAL STANDARD ERROR</strong> <span class="math display">\[s_e=\sqrt{\frac{SSE}{n-k-1}}\]</span> where <span class="math inline">\(k\)</span> is the number of independent variables and <span class="math inline">\(n\)</span> is the sample size.</p>
</div>
<div class="callout-example">
<p><strong>Example:</strong> For the Weight and Exercise model (<span class="math inline">\(k=1\)</span>):</p>
<p><span class="math display">\[s_e=\sqrt{\frac{7.57}{5-1-1}}=1.59\]</span></p>
<p>Adding Calories (<span class="math inline">\(k=2\)</span>) reduces this to:</p>
<p><span class="math display">\[s_e=\sqrt{\frac{1.01}{5-2-1}}=0.71\]</span></p>
<p>The smaller residual standard error confirms that adding Calories improves the model’s fit.</p>
</div>
</section>
</section>
<section id="regression-in-excel" class="level2" data-number="7.4">
<h2 data-number="7.4" class="anchored" data-anchor-id="regression-in-excel"><span class="header-section-number">7.4</span> Regression in Excel</h2>
<p>Excel provides a straightforward way to estimate regression models using the <strong>Data Analysis ToolPak</strong>. If it is not already enabled, go to <code>File → Options → Add-ins → Analysis ToolPak → Go</code> and check the box.</p>
<p><a href="weight_exercise.xlsx" class="btn btn-success"><i class="fa-solid fa-file-excel" aria-label="file-excel"></i> Download Data</a></p>
<p><strong>Simple Regression (Weight and Exercise):</strong></p>
<ol type="1">
<li>Go to <code>Data → Data Analysis → Regression</code></li>
<li>Set the <strong>Input Y Range</strong> to the Weight column</li>
<li>Set the <strong>Input X Range</strong> to the Exercise column</li>
<li>Check <strong>Labels</strong> if your data includes headers</li>
<li>Select an output location and click <code>OK</code></li>
</ol>
<p>Excel will produce a full regression output including the coefficients, <span class="math inline">\(R^2\)</span>, Adjusted <span class="math inline">\(R^2\)</span>, Standard Error, and Anova table — all in one step.</p>
<p><strong>Reading the Excel Output:</strong></p>
<ul>
<li><strong>Intercept</strong> row → <span class="math inline">\(\hat{\alpha}\)</span></li>
<li><strong>X Variable 1</strong> row → <span class="math inline">\(\hat{\beta}\)</span></li>
<li><strong>R Square</strong> → <span class="math inline">\(R^2\)</span></li>
<li><strong>Adjusted R Square</strong> → <span class="math inline">\(\bar{R}^2\)</span></li>
<li><strong>Standard Error</strong> → <span class="math inline">\(s_e\)</span></li>
</ul>
<p><strong>Multiple Regression (Weight, Exercise, and Calories):</strong></p>
<p>Follow the same steps but set the <strong>Input X Range</strong> to include both the Exercise and Calories columns. Excel handles multiple predictors automatically.</p>
<p><strong>Making Predictions:</strong> Once you have the coefficients from the output, use them directly in a formula. For the Advertisement and Price example, if the intercept is in cell B17 and slope in B18:</p>
<pre class="excel"><code>=B17 + B18 * 6</code></pre>
<p>This returns the predicted price for an advertisement budget of <span class="math inline">\(6\)</span>.</p>
</section>
<section id="excel-function-summary" class="level2" data-number="7.5">
<h2 data-number="7.5" class="anchored" data-anchor-id="excel-function-summary"><span class="header-section-number">7.5</span> Excel Function Summary</h2>
<p>Below is a list of the Excel functions and tools used in this section:</p>
<ul>
<li><p><strong>Data Analysis ToolPak → Regression</strong> is the primary tool for estimating regression models in Excel. It returns coefficients, <span class="math inline">\(R^2\)</span>, adjusted <span class="math inline">\(R^2\)</span>, standard error, and the Anova table in a single output.</p></li>
<li><p><code>=SLOPE(y_range, x_range)</code> calculates the slope <span class="math inline">\(\hat{\beta}\)</span> of the simple regression line directly.</p></li>
<li><p><code>=INTERCEPT(y_range, x_range)</code> calculates the intercept <span class="math inline">\(\hat{\alpha}\)</span> of the simple regression line directly.</p></li>
<li><p><code>=FORECAST.LINEAR(x, y_range, x_range)</code> returns the predicted value of <span class="math inline">\(y\)</span> for a given value of <span class="math inline">\(x\)</span> using simple linear regression.</p></li>
<li><p><code>=RSQ(y_range, x_range)</code> returns the <span class="math inline">\(R^2\)</span> for a simple regression.</p></li>
<li><p><code>=STEYX(y_range, x_range)</code> returns the residual standard error <span class="math inline">\(s_e\)</span> for a simple regression.</p></li>
</ul>
</section>
<section id="exercises" class="level2" data-number="7.6">
<h2 data-number="7.6" class="anchored" data-anchor-id="exercises"><span class="header-section-number">7.6</span> Exercises</h2>
<p>The following exercises will help you get practice on Regression Line estimation and interpretation. In particular, the exercises work on:</p>
<ul>
<li>Estimating the slope and intercept.</li>
<li>Calculating measures of goodness of fit.</li>
<li>Prediction using the regression line.</li>
</ul>
<p>Answers are provided below. Try not to peek until you have formulated your own answer and double checked your work for any mistakes.</p>
<section id="exercise-1" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="exercise-1">Exercise 1</h3>
<p>For the following exercises, make your calculations by hand and verify results using Excel functions when possible.</p>
<ol type="1">
<li>Consider the data below. Calculate the deviations from the mean for each variable and use the results to estimate the regression line. Verify your result using Excel. On average, by how much does <em>y</em> increase per unit increase of <em>x</em>?</li>
</ol>
<table class="caption-top table">
<thead>
<tr class="header">
<th style="text-align: center;"><strong>x</strong></th>
<th style="text-align: center;">20</th>
<th style="text-align: center;">21</th>
<th style="text-align: center;">15</th>
<th style="text-align: center;">18</th>
<th style="text-align: center;">25</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;"><strong>y</strong></td>
<td style="text-align: center;">17</td>
<td style="text-align: center;">19</td>
<td style="text-align: center;">12</td>
<td style="text-align: center;">13</td>
<td style="text-align: center;">22</td>
</tr>
</tbody>
</table>
<details>
<summary>
Answer
</summary>
<div style="padding-left: 1.5em;">
<p><em>The regression line is <span class="math inline">\(\hat{y}=-4.93+1.09x\)</span>. For each unit increase in <span class="math inline">\(x\)</span>, <span class="math inline">\(y\)</span> increases on average by <span class="math inline">\(1.09\)</span>.</em></p>
<p><em>Start with the deviations from the mean (<span class="math inline">\(\bar{x}=19.8\)</span>, <span class="math inline">\(\bar{y}=16.6\)</span>):</em></p>
<table class="caption-top table">
<colgroup>
<col style="width: 9%">
<col style="width: 9%">
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 12%">
<col style="width: 26%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: center;"><span class="math inline">\(x_i\)</span></th>
<th style="text-align: center;"><span class="math inline">\(y_i\)</span></th>
<th style="text-align: center;"><span class="math inline">\(x_i-\bar{x}\)</span></th>
<th style="text-align: center;"><span class="math inline">\(y_i-\bar{y}\)</span></th>
<th style="text-align: center;">Product</th>
<th style="text-align: center;"><span class="math inline">\((x_i-\bar{x})^2\)</span></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">20</td>
<td style="text-align: center;">17</td>
<td style="text-align: center;"><span class="math inline">\(0.2\)</span></td>
<td style="text-align: center;"><span class="math inline">\(0.4\)</span></td>
<td style="text-align: center;"><span class="math inline">\(0.08\)</span></td>
<td style="text-align: center;"><span class="math inline">\(0.04\)</span></td>
</tr>
<tr class="even">
<td style="text-align: center;">21</td>
<td style="text-align: center;">19</td>
<td style="text-align: center;"><span class="math inline">\(1.2\)</span></td>
<td style="text-align: center;"><span class="math inline">\(2.4\)</span></td>
<td style="text-align: center;"><span class="math inline">\(2.88\)</span></td>
<td style="text-align: center;"><span class="math inline">\(1.44\)</span></td>
</tr>
<tr class="odd">
<td style="text-align: center;">15</td>
<td style="text-align: center;">12</td>
<td style="text-align: center;"><span class="math inline">\(-4.8\)</span></td>
<td style="text-align: center;"><span class="math inline">\(-4.6\)</span></td>
<td style="text-align: center;"><span class="math inline">\(22.08\)</span></td>
<td style="text-align: center;"><span class="math inline">\(23.04\)</span></td>
</tr>
<tr class="even">
<td style="text-align: center;">18</td>
<td style="text-align: center;">13</td>
<td style="text-align: center;"><span class="math inline">\(-1.8\)</span></td>
<td style="text-align: center;"><span class="math inline">\(-3.6\)</span></td>
<td style="text-align: center;"><span class="math inline">\(6.48\)</span></td>
<td style="text-align: center;"><span class="math inline">\(3.24\)</span></td>
</tr>
<tr class="odd">
<td style="text-align: center;">25</td>
<td style="text-align: center;">22</td>
<td style="text-align: center;"><span class="math inline">\(5.2\)</span></td>
<td style="text-align: center;"><span class="math inline">\(5.4\)</span></td>
<td style="text-align: center;"><span class="math inline">\(28.08\)</span></td>
<td style="text-align: center;"><span class="math inline">\(27.04\)</span></td>
</tr>
</tbody>
</table>
<p><span class="math display">\[\hat{\beta}=\frac{\sum(x_i-\bar{x})(y_i-\bar{y})}{\sum(x_i-\bar{x})^2}=\frac{59.6}{54.8}=1.09\]</span></p>
<p><span class="math display">\[\hat{\alpha}=\bar{y}-\hat{\beta}\bar{x}=16.6-1.09(19.8)=-4.93\]</span></p>
<p><em>To verify in Excel, enter x in column A and y in column B and use:</em></p>
<ul>
<li><code>=SLOPE(B2:B6, A2:A6)</code> → <span class="math inline">\(1.09\)</span></li>
<li><code>=INTERCEPT(B2:B6, A2:A6)</code> → <span class="math inline">\(-4.93\)</span></li>
</ul>
</div>
</details>
<ol start="2" type="1">
<li>Calculate <em>SST</em>, <em>SSR</em>, and <em>SSE</em>. What is the <span class="math inline">\(R^2\)</span>? What is the Standard Error estimate? Is the regression line a good fit for the data?</li>
</ol>
<details>
<summary>
Answer
</summary>
<div style="padding-left: 1.5em;">
<p><em>SST is <span class="math inline">\(69.2\)</span>, SSR is <span class="math inline">\(64.82\)</span> and SSE is <span class="math inline">\(4.38\)</span> (note that <span class="math inline">\(SSR+SSE=SST\)</span>). The <span class="math inline">\(R^2\)</span> is <span class="math inline">\(\frac{SSR}{SST}=0.94\)</span> and the Standard Error estimate is <span class="math inline">\(1.21\)</span>. Both indicate a great fit of the regression line to the data.</em></p>
<p><em>In Excel, with x in column A and y in column B:</em></p>
<ul>
<li><code>=DEVSQ(B2:B6)</code> → <span class="math inline">\(SST = 69.2\)</span></li>
<li><code>=RSQ(B2:B6, A2:A6)</code> → <span class="math inline">\(R^2 = 0.94\)</span></li>
<li><code>=STEYX(B2:B6, A2:A6)</code> → <span class="math inline">\(s_e = 1.21\)</span></li>
</ul>
<p><em>Then <span class="math inline">\(SSR = R^2 \times SST = 64.82\)</span> and <span class="math inline">\(SSE = SST - SSR = 4.38\)</span>. You can also obtain all of these at once from <code>Data → Data Analysis → Regression</code>, which reports the ANOVA table (SSR, SSE, SST), <span class="math inline">\(R^2\)</span>, and the Standard Error in a single output.</em></p>
</div>
</details>
<ol start="3" type="1">
<li>Assume that <em>x</em> is observed to be <em>32</em>. What is your prediction of <em>y</em>? How confident are you in this prediction?</li>
</ol>
<details>
<summary>
Answer
</summary>
<div style="padding-left: 1.5em;">
<p><em>If <span class="math inline">\(x=32\)</span> then <span class="math inline">\(\hat{y}=-4.93+1.09(32)=29.87\)</span>. The regression is a good fit, so we can feel good about our prediction. However, we would be concerned about the small sample size of the data.</em></p>
<p><em>In Excel:</em></p>
<ul>
<li><code>=FORECAST.LINEAR(32, B2:B6, A2:A6)</code> → <span class="math inline">\(29.87\)</span></li>
</ul>
</div>
</details>
</section>
<section id="exercise-2" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="exercise-2">Exercise 2</h3>
<p>You will need the <strong>Education</strong> data set to answer this question. You can download it here:</p>
<p><a href="Education.xlsx" class="btn btn-success"><i class="fa-solid fa-file-excel" aria-label="file-excel"></i> Download Data</a></p>
<p>The data shows the years of education (<em>Education</em>) and the annual salary in thousands (<em>Salary</em>) for a sample of <span class="math inline">\(100\)</span> people.</p>
<ol type="1">
<li>Estimate the regression line using Excel. By how much does an extra year of education increase the annual salary on average? What is the salary of someone without any education?</li>
</ol>
<details>
<summary>
Answer
</summary>
<div style="padding-left: 1.5em;">
<p><em>An extra year of education increases the annual salary by about <span class="math inline">\(\$5,300\)</span> (the slope). A person with no education would be expected to earn about <span class="math inline">\(\$17,258\)</span> (the intercept).</em></p>
<p><em>In Excel, assuming <code>Salary</code> is in column B and <code>Education</code> is in column C:</em></p>
<ul>
<li><code>=SLOPE(B2:B101, C2:C101)</code> → <span class="math inline">\(5.30\)</span></li>
<li><code>=INTERCEPT(B2:B101, C2:C101)</code> → <span class="math inline">\(17.26\)</span></li>
</ul>
<p><em>You can also use <code>Data → Data Analysis → Regression</code> with <code>Salary</code> as the Input Y Range and <code>Education</code> as the Input X Range.</em></p>
</div>
</details>
<ol start="2" type="1">
<li>Confirm that the regression line is a good fit for the data. What is the estimated salary of a person with <span class="math inline">\(16\)</span> years of education?</li>
</ol>
<details>
<summary>
Answer
</summary>
<div style="padding-left: 1.5em;">
<p><em>The <span class="math inline">\(R^2\)</span> is <span class="math inline">\(0.67\)</span> and the standard error is about <span class="math inline">\(21\)</span>. The line is a moderately good fit. A person with <span class="math inline">\(16\)</span> years of education is predicted to earn about <span class="math inline">\(\$102,000\)</span>.</em></p>
<p><em>In Excel:</em></p>
<ul>
<li><code>=RSQ(B2:B101, C2:C101)</code> → <span class="math inline">\(0.67\)</span></li>
<li><code>=STEYX(B2:B101, C2:C101)</code> → <span class="math inline">\(21\)</span></li>
<li><code>=FORECAST.LINEAR(16, B2:B101, C2:C101)</code> → <span class="math inline">\(102.08\)</span></li>
</ul>
</div>
</details>
</section>
<section id="exercise-3" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="exercise-3">Exercise 3</h3>
<p>You will need the <strong>FoodSpend</strong> data set to answer this question. You can download it here:</p>
<p><a href="FoodSpend.xlsx" class="btn btn-success"><i class="fa-solid fa-file-excel" aria-label="file-excel"></i> Download Data</a></p>
<ol type="1">
<li>Remove any observations with missing values. Create a dummy variable that is equal to <span class="math inline">\(1\)</span> if an individual owns a home and <span class="math inline">\(0\)</span> if the individual does not. Find the mean of your dummy variable. What proportion of the sample owns a home?</li>
</ol>
<details>
<summary>
Answer
</summary>
<div style="padding-left: 1.5em;">
<p><em>Approximately <span class="math inline">\(36\%\)</span> of the sample owns a home (mean <span class="math inline">\(=0.3625\)</span>).</em></p>
<p><em>In Excel, assuming <code>OwnHome</code> is in column A and <code>Food</code> is in column B, first delete any rows with missing values. Then add a helper column C with the dummy variable:</em></p>
<pre class="excel"><code>=IF(A2="Yes", 1, 0)</code></pre>
<p><em>Copy it down for all rows and take the average:</em></p>
<ul>
<li><code>=AVERAGE(C2:C81)</code> → <span class="math inline">\(0.3625\)</span></li>
</ul>
</div>
</details>
<ol start="2" type="1">
<li>Run a regression with <em>Food</em> as the dependent variable and your dummy variable as the independent variable. What is the interpretation of the intercept and slope?</li>
</ol>
<details>
<summary>
Answer
</summary>
<div style="padding-left: 1.5em;">
<p><em>The intercept (<span class="math inline">\(\approx 6473\)</span>) is the average food expenditure of individuals without homes. The slope (<span class="math inline">\(\approx -3418\)</span>) is the difference in food expenditure between individuals who own a home and those who do not — home owners spend about <span class="math inline">\(\$3,418\)</span> less on food than non-owners.</em></p>
<p><em>In Excel, with <code>Food</code> in column B and the dummy in column C:</em></p>
<ul>
<li><code>=INTERCEPT(B2:B81, C2:C81)</code> → <span class="math inline">\(6473\)</span></li>
<li><code>=SLOPE(B2:B81, C2:C81)</code> → <span class="math inline">\(-3418\)</span></li>
</ul>
</div>
</details>
<ol start="3" type="1">
<li>Now run a regression with your dummy variable as the dependent variable and <em>Food</em> as the independent variable. What is the interpretation of the intercept and slope? Hint: you might want to plot the scatter diagram and the regression line.</li>
</ol>
<details>
<summary>
Answer
</summary>
<div style="padding-left: 1.5em;">
<p><em>The regression line is <span class="math inline">\(\widehat{dummy}=1.432-0.000204\,Food\)</span>. This is a linear probability model: it predicts the likelihood of owning a home from food expenditure. The slope tells us how that likelihood changes as food expenditure increases by one dollar — in general, the likelihood of owning a home decreases as food expenditure increases. The scatter plot shows that most home owners have food expenditures below <span class="math inline">\(\$6,000\)</span>, while non-owners are mostly above it.</em></p>
<p><em>In Excel, with the dummy in column C and <code>Food</code> in column B:</em></p>
<ul>
<li><code>=INTERCEPT(C2:C81, B2:B81)</code> → <span class="math inline">\(1.432\)</span></li>
<li><code>=SLOPE(C2:C81, B2:B81)</code> → <span class="math inline">\(-0.000204\)</span></li>
</ul>
<p><em>For the scatter plot, select <code>Food</code> and the dummy variable, go to <code>Insert → Charts → Scatter</code>, and add a linear trend line by right-clicking a point and choosing <code>Add Trendline → Linear</code>.</em></p>
</div>
</details>
</section>
<section id="exercise-4" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="exercise-4">Exercise 4</h3>
<p>You will need the <strong>Population</strong> data set to answer this question. You can download it here:</p>
<p><a href="Population.xlsx" class="btn btn-success"><i class="fa-solid fa-file-excel" aria-label="file-excel"></i> Download Data</a></p>
<ol type="1">
<li>Run a regression of <em>Population</em> on <em>Year</em> for Japan. How well does the regression line fit the data?</li>
</ol>
<details>
<summary>
Answer
</summary>
<div style="padding-left: 1.5em;">
<p><em>With an <span class="math inline">\(R^2=0.81\)</span>, the model fits the data very well.</em></p>
<p><em>In Excel, first isolate Japan: select the data, go to <code>Data → Filter</code>, and filter <code>Country.Name</code> to <code>Japan</code>. Copy the <span class="math inline">\(62\)</span> Japan rows to a new sheet. Assuming <code>Year</code> is in column C and <code>Population</code> is in column D:</em></p>
<ul>
<li><code>=RSQ(D2:D63, C2:C63)</code> → <span class="math inline">\(0.81\)</span></li>
</ul>
</div>
</details>
<ol start="2" type="1">
<li>Create a prediction for Japan’s population in 2030. What is your prediction?</li>
</ol>
<details>
<summary>
Answer
</summary>
<div style="padding-left: 1.5em;">
<p><em>The prediction for <span class="math inline">\(2030\)</span> is about <span class="math inline">\(140\)</span> million people (<span class="math inline">\(140{,}268{,}585\)</span>).</em></p>
<p><em>In Excel:</em></p>
<ul>
<li><code>=FORECAST.LINEAR(2030, D2:D63, C2:C63)</code> → <span class="math inline">\(140{,}268{,}585\)</span></li>
</ul>
</div>
</details>
<ol start="3" type="1">
<li>Create a scatter diagram and include the regression line. How confident are you of your prediction after looking at the diagram?</li>
</ol>
<details>
<summary>
Answer
</summary>
<div style="padding-left: 1.5em;">
<p><em>After looking at the scatter plot, it seems unlikely that the population in Japan will hit <span class="math inline">\(140\)</span> million. In the most recent years the population has been decreasing, so the straight-line trend overstates the future population — the prediction should be treated with caution.</em></p>
<p><em>In Excel, select the <code>Year</code> and <code>Population</code> columns for Japan, go to <code>Insert → Charts → Scatter</code>, and add a linear trend line by right-clicking a point and choosing <code>Add Trendline → Linear</code>.</em></p>
</div>
</details>


</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    // For code content inside modals, clipBoardJS needs to be initialized with a container option
    // TODO: Check when it could be a function (https://github.com/zenorocha/clipboard.js/issues/860)
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./RegressionI.html" class="pagination-link" aria-label="Regression I">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Regression I</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./ProbabilityI.html" class="pagination-link" aria-label="Probability I">
        <span class="nav-page-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Probability I</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
<p>Business Statistics by J. Alejandro Gelves.</p>
</div>   
    <div class="nav-footer-center">
      &nbsp;
    </div>
    <div class="nav-footer-right">
<p>This book was built with <a href="https://quarto.org/">Quarto</a>.</p>
</div>
  </div>
</footer>




</body></html>